Debugger Class Reference
helper functions and flags to aid in debugging aspects of the engine
#include <Debugger.h>
Public Types
enum LogType {
INFO
, WARNING
, ERROR
, ENGINE
,
ALL
 }
Enum of different log types.
Public Member Functions
std::string DebugVec3 (glm::vec3 a)
turns a vec3 into a string for console output
glm::vec3 ConvertPlayerToTerrainPosition (glm::vec3 playerPosition, float terrainSize, float vertexHeight)
Calculates and returns the vec3 position of the player in terrain coords.
void OpenLogger ()
Used to open the log file and save its pointer.
void AppendLogger (std::string fromFile, std::string outputString)
Appends a string to the log file with current time of the system and information where the append came from.
void CloseLogger ()
closes the log file on exit
Static Public Member Functions
static Debugger * GetInstance ()
Public Attributes
bool debugToConsole = false
flag for enabling/disabling debug and error information in the console
bool debugCollisionsToConsole = false
flag for enabling/disabling debug information about collisions in the console
bool debugFSMToConsole = false
flag for enabling/disabling debug information about FSM in the console
bool debugWeapons = false
flag for enabling/disabling debug information about weapons in the console
bool debugTokensToConsole = false
flag for enabling/disabling debug information about tokens in the console
bool debugAnimationsToConsole = false
flag for enabling/disabling debug information about animations in the console
bool debugMD2ToConsole = false
flag for enabling/disabling debug information about MD2 in the console
bool debugPlayerPos = false
flag for enabling/disabling debug information about player position in the the game screen
bool stickyFPSCounter = false
flag for enabling/disabling debug information about framerate in the game screen
bool debugInfoToLogFile = false
flag for enabling/disabling debug information about info types to the log file
bool debugErrorsToLogFile = false
flag for enabling/disabling debug information about error types to the log file
bool debugEngineToLogFile = true
flag for enabling/disabling debug information about engine types to the log file
bool debugWarningToLogFile = false
Flag for enabling/disabling debug information about warning types to the log file.
bool drawDebugPanel = false
flag for enabling/disabling the debug panel
bool noPlayerYClip = true
flag for enabling and disabling the player Y position clipping
GLFWwindow * windowRef = nullptr
reference to a GLFW window
std::string logFilePath
String of log file path.
LogType type = ENGINE
Global log type.
Static Protected Attributes
static Debugger * instance = 0
Detailed Description
helper functions and flags to aid in debugging aspects of the engine
Definition at line 30 of file Debugger.h.
Member Function Documentation
AppendLogger()
void Debugger::AppendLogger (std::string fromFile, std::string outputString)
Appends a string to the log file with current time of the system and information where the append came from.
Parameters
type
fromFile
outputString
Definition at line 50 of file Debugger.cpp.
{
    if(logFile == nullptr) return;
    std::string ty = LogTypeToString(type);
    std::string s, t;
    auto time = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
    s = " " + fromFile + " :: " + outputString + "\n";
#if _WIN32
    char buffer[256];
    t = ctime_s(buffer, 256, &time);
#elif _APPLE_
    t = ctime(&time);
#endif
    t.erase(std::remove(t.begin(), t.end(), '\n'), t.end());
    //time, type, string to append
    fprintf(logFile, "%s :: %s :: %s",t.c_str(), ty.c_str(), s.c_str());
}
References type.
Referenced by Enemy::handleMessage(), Enemy::Update(), and Enemy::~Enemy().
ConvertPlayerToTerrainPosition()
glm::vec3 Debugger::ConvertPlayerToTerrainPosition (glm::vec3 playerPosition, float terrainSize, float vertexHeight)
Calculates and returns the vec3 position of the player in terrain coords.
Parameters
playerPosition
Returns
vec3 of the players position in relation to the terrain vertex data
Definition at line 22 of file Debugger.cpp.
{
    float worldx, worldz, worldToTerrainScaleFactor;
    worldToTerrainScaleFactor = terrainSize / 409.0f;
    worldx = playerPosition.x * worldToTerrainScaleFactor;
    worldz = playerPosition.z * worldToTerrainScaleFactor;
    glm::vec3 terrainPos = glm::vec3(worldx, vertexHeight, worldz);
    return terrainPos;
}
DebugVec3()
std::string Debugger::DebugVec3 (glm::vec3 a)
turns a vec3 into a string for console output
Parameters
Vec3 a
Returns
string - string value with each XYZ of a given vec3
Definition at line 16 of file Debugger.cpp.
{
    std::string b = "X: " + std::to_string(a.x) + " -- Y: " + std::to_string(a.y) + " -- Z: " + std::to_string(a.z);
    return b;
}
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Debugger.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Debugger.cpp