GameObject Class Reference
Class that holds the main information of a game object, that is abstracted for more specific reasons.
#include <GameObject.h>
Public Member Functions
GameObject ()
Default constructor.
GameObject (glm::vec3 p, glm::vec3 rot, float s, Renderer *gameRenderer)
Constructor.
virtual void Update (float time)
Updates the classes functionality.
void SetModel (Model m)
Sets a new model.
void SetShader (Shader s)
Set new shader.
void SetRotate (bool r)
Set rotate bool.
void SetRotation (glm::vec3 r)
Sets the rotation value.
void SetPos (glm::vec3 p)
Sets the position.
void SetScale (float size)
Sets the scale value.
glm::vec3 GetPos () const
Gets the position value.
glm::vec3 GetRotation () const
Gets the rotation value.
float GetScale () const
Gets the scale value.
Model GetModel ()
Gets the model.
Shader GetShader ()
Gets the shader.
void SetType (std::string t)
Sets the type of object.
std::string GetType ()
Gets the type of object.
void SetBoundingBox (BoundingBox b)
Sets gameobject's bounding box object.
BoundingBox GetBoundingBox ()
Gets a gameobjec's boundingbox object.
void SetCollisionTag (BoundingBox::CollisionTag t)
Sets tag of a given object.
BoundingBox::CollisionTag GetTag ()
Gets the objects tag.
void SetName (std::string n)
Sets the name of a game object.
std::string GetName ()
Gets the name of a Gameobject.
virtual void Render (View lens, float time, Renderer *gameRenderer)
Renders the game object.
bool GetRotate ()
Gets the rotate bool.
int GetId ()
Gets the id.
void SetId (int i)
Sets the id.
virtual bool handleMessage (const Telegram message)
Handles messages from other game objects.
virtual bool Kill ()
Kill information used in other game objects.
std::string GetScriptName () const
Gets the script name.
void SetScriptName (const std::string name)
Sets the script name.
virtual std::string StreamValues ()
Returns the streamed values for the game object.
Detailed Description
Class that holds the main information of a game object, that is abstracted for more specific reasons.
Author
Christopher Logan
Version
01
Date
25/03/2021
Todo
Todo Add collisions
@bugs none to be seen
Definition at line 24 of file GameObject.h.
Constructor & Destructor Documentation
GameObject()
GameObject::GameObject (glm::vec3 p, glm::vec3 rot, float s, Renderer * gameRenderer) [inline]
Constructor.
Parameters
p - The position
fixRot - The fixed rotation
rot - The new rotation
s - The scale
Definition at line 39 of file GameObject.h.
{ pos = p; rotation = rot; scale = s; rotate = false; boundingBox = BoundingBox();}
Member Function Documentation
GetBoundingBox()
BoundingBox GameObject::GetBoundingBox () [inline]
Gets a gameobjec's boundingbox object.
Returns
BoundingBox
Definition at line 135 of file GameObject.h.
{return boundingBox;}
GetId()
int GameObject::GetId () [inline]
Gets the id.
Returns
the game object id
Definition at line 180 of file GameObject.h.
{ return id; }
Referenced by EntityManager::RemoveEntity().
GetModel()
Model GameObject::GetModel () [inline]
Gets the model.
Returns
model
Definition at line 105 of file GameObject.h.
{ return model; }
Referenced by GameAssetFactory::GetGameObject(), and GameAssetFactory::GetGameObjectSave().
GetName()
std::string GameObject::GetName () [inline]
Gets the name of a Gameobject.
Returns
string name
Definition at line 160 of file GameObject.h.
{return name;}
GetPos()
glm::vec3 GameObject::GetPos () const [inline]
Gets the position value.
Returns
pos
Definition at line 87 of file GameObject.h.
{ return pos; }
GetRotate()
bool GameObject::GetRotate () [inline]
Gets the rotate bool.
Returns
true if the object needs to be rotated when rendering
Definition at line 174 of file GameObject.h.
{ return rotate; }
GetRotation()
glm::vec3 GameObject::GetRotation () const [inline]
Gets the rotation value.
Returns
rotation
Definition at line 93 of file GameObject.h.
{ return rotation; }
GetScale()
float GameObject::GetScale () const [inline]
Gets the scale value.
Returns
scale
Definition at line 99 of file GameObject.h.
{ return scale; }
GetScriptName()
std::string GameObject::GetScriptName () const [inline]
Gets the script name.
Returns
scriptName
Definition at line 204 of file GameObject.h.
{ return scriptName; }
GetShader()
Shader GameObject::GetShader () [inline]
Gets the shader.
Returns
shader
Definition at line 111 of file GameObject.h.
{ return shader; }
GetTag()
BoundingBox::CollisionTag GameObject::GetTag () [inline]
Gets the objects tag.
Returns
tag
Definition at line 148 of file GameObject.h.
{return tag;}
GetType()
std::string GameObject::GetType () [inline]
Gets the type of object.
Returns
type
Definition at line 123 of file GameObject.h.
{ return type; }
handleMessage()
virtual bool GameObject::handleMessage (const Telegram message) [inline], [virtual]
Handles messages from other game objects.
Returns
false by default
Reimplemented in Enemy.
Definition at line 192 of file GameObject.h.
{ return false; }
Kill()
virtual bool GameObject::Kill () [inline], [virtual]
Kill information used in other game objects.
Returns
false by default
Reimplemented in Token, and Enemy.
Definition at line 198 of file GameObject.h.
{ return false; }
Render()
void GameObject::Render (View lens, float time, Renderer * gameRenderer) [virtual]
Renders the game object.
Parameters
lens - The lens values for projection, positons, ect
time - The deltatime value
gameRenderer - the renderer pointer itself
Reimplemented in Token, Player, and Enemy.
Definition at line 9 of file GameObject.cpp.
{
    model.Render(lens, shader, pos, rotation, scale, rotate, time, 0, gameRenderer, false);
}
SetBoundingBox()
void GameObject::SetBoundingBox (BoundingBox b) [inline]
Sets gameobject's bounding box object.
Parameters
b
Definition at line 129 of file GameObject.h.
{boundingBox = b;}
Referenced by GameAssetFactory::GetGameObject(), and GameAssetFactory::GetGameObjectSave().
SetCollisionTag()
void GameObject::SetCollisionTag (BoundingBox::CollisionTag t) [inline]
Sets tag of a given object.
Parameters
t
Definition at line 142 of file GameObject.h.
{tag = t;}
Referenced by GameAssetFactory::GetGameObject(), and GameAssetFactory::GetGameObjectSave().
SetId()
void GameObject::SetId (int i) [inline]
Sets the id.
Parameters
i - the id to be set
Definition at line 186 of file GameObject.h.
{ id = i; }
Referenced by GameAssetFactory::GetGameObject(), and GameAssetFactory::GetGameObjectSave().
SetModel()
void GameObject::SetModel (Model m) [inline]
Sets a new model.
Parameters
m - The new value
Definition at line 51 of file GameObject.h.
{ model = m; }
SetName()
void GameObject::SetName (std::string n) [inline]
Sets the name of a game object.
Parameters
n
Definition at line 154 of file GameObject.h.
{name = n;}
Referenced by GameAssetFactory::GetGameObject(), and GameAssetFactory::GetGameObjectSave().
SetPos()
void GameObject::SetPos (glm::vec3 p) [inline]
Sets the position.
Parameters
p - The new value
Definition at line 75 of file GameObject.h.
{ pos = p; }
SetRotate()
void GameObject::SetRotate (bool r) [inline]
Set rotate bool.
Parameters
r - The new value
Definition at line 63 of file GameObject.h.
{ rotate = r; }
SetRotation()
void GameObject::SetRotation (glm::vec3 r) [inline]
Sets the rotation value.
Parameters
r - The new value
Definition at line 69 of file GameObject.h.
{ rotation = r; }
SetScale()
void GameObject::SetScale (float size) [inline]
Sets the scale value.
Parameters
size - The new value
Definition at line 81 of file GameObject.h.
{ scale = size; }
SetScriptName()
void GameObject::SetScriptName (const std::string name) [inline]
Sets the script name.
Parameters
name - The script name being set
Definition at line 210 of file GameObject.h.
{ scriptName = name; }
SetShader()
void GameObject::SetShader (Shader s) [inline]
Set new shader.
Parameters
s - The new value
Definition at line 57 of file GameObject.h.
{ shader = s; }
SetType()
void GameObject::SetType (std::string t) [inline]
Sets the type of object.
Parameters
t - The type
Definition at line 117 of file GameObject.h.
{ type = t; }
Referenced by GameAssetFactory::GetGameObject(), and GameAssetFactory::GetGameObjectSave().
StreamValues()
std::string GameObject::StreamValues () [virtual]
Returns the streamed values for the game object.
Returns
streamed Values of the game object
Reimplemented in Player, and Enemy.
Definition at line 14 of file GameObject.cpp.
{
    return GetType() + " " + GetScriptName() + " " + std::to_string(GetScale()) + " " + std::to_string(pos.x) + " " + std::to_string(pos.y) + " " + std::to_string(pos.z) + "\n";
}
Update()
void GameObject::Update (float time) [virtual]
Updates the classes functionality.
Parameters
time - The time between frames
Reimplemented in Water, Token, Static, Player, and Enemy.
Definition at line 4 of file GameObject.cpp.
{
    std::cout << "GAMEOBJECT::ERROR::UPDATE::TYPE_NOT_SET" << std::endl;
}
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/GameObject.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/GameObject.cpp