Window Class Reference
Public Member Functions
virtual void Init (std::string title, int h, int w)
Initilises the window class, setting the title height and width.
virtual void Buffer ()=0
Calls the buffer.
virtual void GameInput (float deltaTime)
Holds the game input logic for the keyboard, uses the input variable to set the actual keys.
virtual void Terminate ()
Sets the termination information for the class.
virtual void FrameBuffer ()
Calls the frame buffer.
virtual Camera GetCamera ()
Getter for the camera.
virtual void UpdateCamera (glm::vec3 p)
Updates the camera position.
virtual void MouseMove ()
Sets mouse movmenet.
virtual View GetLens ()
Getter for the lens.
virtual void Update ()
Updates the window for things such as time, lens values.
virtual float GetTime ()
Getter for deltaTime.
virtual bool Running ()
Checks if the window is running still.
virtual bool GetDisplay ()
Gets the display value.
virtual bool GetWeaponFire ()
virtual void SetRefWindow (Window *w)
virtual float GetCurrentTime ()
virtual void ToggleFullScreen (bool change)
Detailed Description
Definition at line 11 of file Window.h.
Member Function Documentation
GameInput()
virtual void Window::GameInput (float deltaTime) [inline], [virtual]
Holds the game input logic for the keyboard, uses the input variable to set the actual keys.
Parameters
deltaTime - Takes in delta time for the movement of the camera
Reimplemented in GlfwWindow.
Definition at line 31 of file Window.h.
{}
Referenced by Engine::Run().
GetCamera()
virtual Camera Window::GetCamera () [inline], [virtual]
Getter for the camera.
Returns
camera
Reimplemented in GlfwWindow.
Definition at line 48 of file Window.h.
{ Camera c(glm::vec3(0, 0, 0)); return c; }
GetDisplay()
virtual bool Window::GetDisplay () [inline], [virtual]
Gets the display value.
Returns
exitDisplay
Reimplemented in GlfwWindow.
Definition at line 87 of file Window.h.
{ return false; }
Referenced by Engine::Run().
GetLens()
virtual View Window::GetLens () [inline], [virtual]
Getter for the lens.
Returns
lens
Reimplemented in GlfwWindow.
Definition at line 64 of file Window.h.
{ return View(); }
GetTime()
virtual float Window::GetTime () [inline], [virtual]
Getter for deltaTime.
Returns
gameTime.DetaTime()
Reimplemented in GlfwWindow.
Definition at line 75 of file Window.h.
{ return 0; }
Referenced by Engine::Run().
Init()
virtual void Window::Init (std::string title, int h, int w) [inline], [virtual]
Initilises the window class, setting the title height and width.
Parameters
title - The title of the window
h - The height of the window
w - The width of the window
Reimplemented in GlfwWindow.
Definition at line 20 of file Window.h.
{ }
The documentation for this class was generated from the following file:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Window.h