BoundingBox Class Reference
Class to control and generate boudningbox information for a given object.
#include <BoundingBox.h>
Public Types
enum CollisionTag {
PLAYER
, TOKEN
, STATIC_OBJECT
, ENEMY
,
WATER
 }
Collision tag used for collision checking on a object.
Public Member Functions
BoundingBox ()=default
Bounding box constructor with empty objects.
BoundingBox (std::vector< glm::vec3 > v, std::vector< int > i)
Bounding box constructor with vertex and indice data.
void SetVertexData (std::vector< glm::vec3 > v)
Sets the vertex data of a bounding box.
void SetIndiceData (std::vector< int > i)
Sets the indice data of a bounding box.
void SetNormalsData (std::vector< glm::vec3 > n)
Sets the normals data of a bounding box.
std::vector< glm::vec3 > GetVertexData ()
Gets vertex data of a bounding box.
std::vector< int > GetIndiceData ()
Gets indice data of a bounding box.
std::vector< glm::vec3 > GetNormalData ()
Gets normal data of a bounding box.
BoundingBox GenerateBoundingBox (Mesh *mesh)
Takes a mesh and generates a basix bounding box based off min and max values of the mesh in X,Y,Z directions.
void GenerateBoundingBoxNormals ()
Generates normals of the bounding box.
Detailed Description
Class to control and generate boudningbox information for a given object.
Author
Bryce Standley
Date
06/04/2021
Class to hold all collision and bounding box information of a game object
Todo
Todo Implement bounding box collisions
Definition at line 18 of file BoundingBox.h.
Constructor & Destructor Documentation
BoundingBox()
BoundingBox::BoundingBox (std::vector< glm::vec3 > v, std::vector< int > i) [inline]
Bounding box constructor with vertex and indice data.
Parameters
vector vec3 v
vector int i
Definition at line 30 of file BoundingBox.h.
{vertex = v; indice = i;};
Member Function Documentation
GenerateBoundingBox()
BoundingBox BoundingBox::GenerateBoundingBox (Mesh * mesh)
Takes a mesh and generates a basix bounding box based off min and max values of the mesh in X,Y,Z directions.
Parameters
mesh
Returns
boundingBox
Definition at line 3 of file BoundingBox.cpp.
{
    float minX = 0.0f, minY = 0.0f, minZ = 0.0f;
    float maxX = 0.0f, maxY = 0.0f, maxZ = 0.0f;
    glm::vec3 size, origin;
    glm::mat4 transform;
    for(Vertex & vertice : mesh->vertices)
    {
        if(minX > vertice.Position.x) {minX = vertice.Position.x;}
        if(maxX < vertice.Position.x) {maxX = vertice.Position.x;}
        if(minY > vertice.Position.y) {minY = vertice.Position.y;}
        if(maxY > vertice.Position.y) {maxY = vertice.Position.y;}
        if(minZ > vertice.Position.z) {minZ = vertice.Position.z;}
        if(maxZ > vertice.Position.z) {maxZ = vertice.Position.z;}
    }
    std::vector<glm::vec3> box;
    std::vector<int> ind;
    //All vertex data for all 8 required vertices
    box.emplace_back(glm::vec3(minX, maxY, maxZ));
    box.emplace_back(glm::vec3(maxX, maxY, maxZ));
    box.emplace_back(glm::vec3(maxX, minY, maxZ));
    box.emplace_back(glm::vec3(minX, minY, maxZ));
    box.emplace_back(glm::vec3(minX, maxY, minZ));
    box.emplace_back(glm::vec3(maxX, maxY, minZ));
    box.emplace_back(glm::vec3(maxX, minY, minZ));
    box.emplace_back(glm::vec3(minX, minY, minZ));
    size = glm::vec3(maxX-minX, maxY-minY, maxZ-minZ);
    origin = glm::vec3((minX+maxX)/2, (minY + maxY)/2, (minZ + maxZ)/2);
    transform = glm::translate(glm::mat4(1), origin) * glm::scale(glm::mat4(1), size);
    //index of all the triangles
    int indi[] = {
            // front
            0, 1, 2,
            2, 3, 0,
            // right
            1, 5, 6,
            6, 2, 1,
            // back
            7, 6, 5,
            5, 4, 7,
            // left
            4, 0, 3,
            3, 7, 4,
            // bottom
            4, 5, 1,
            1, 0, 4,
            // top
            3, 2, 6,
            6, 7, 3
    };
    ind.insert(ind.begin(), std::begin(indi), std::end(indi));
    GenerateBoundingBoxNormals();
    return BoundingBox(box, ind);
}
References GenerateBoundingBoxNormals().
Referenced by GameAssetFactory::GetGameObject(), and GameAssetFactory::GetGameObjectSave().
GetIndiceData()
std::vector<int> BoundingBox::GetIndiceData () [inline]
Gets indice data of a bounding box.
Returns
vector int
Definition at line 60 of file BoundingBox.h.
{return indice;}
GetNormalData()
std::vector<glm::vec3> BoundingBox::GetNormalData () [inline]
Gets normal data of a bounding box.
Returns
vector vec3
Definition at line 66 of file BoundingBox.h.
{return normals;}
GetVertexData()
std::vector<glm::vec3> BoundingBox::GetVertexData () [inline]
Gets vertex data of a bounding box.
Returns
vector vec3
Definition at line 54 of file BoundingBox.h.
{return vertex;}
SetIndiceData()
void BoundingBox::SetIndiceData (std::vector< int > i) [inline]
Sets the indice data of a bounding box.
Parameters
vector int i
Definition at line 42 of file BoundingBox.h.
{indice = i;}
SetNormalsData()
void BoundingBox::SetNormalsData (std::vector< glm::vec3 > n) [inline]
Sets the normals data of a bounding box.
Parameters
vector vec3 n
Definition at line 48 of file BoundingBox.h.
{normals = n;}
SetVertexData()
void BoundingBox::SetVertexData (std::vector< glm::vec3 > v) [inline]
Sets the vertex data of a bounding box.
Parameters
vector vec3 v
Definition at line 36 of file BoundingBox.h.
{vertex = v;}
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/BoundingBox.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/BoundingBox.cpp