Model Class Reference
Holds the model information of objects, can be md2 or Fbx models.
#include <Model.h>
Public Member Functions
Model ()
default constructor
Model (std::string const &path, Renderer *r, bool check)
Model constructor that takes various parameters.
Model (std::string const &path, Renderer *r, bool check, std::string pathTexture, bool anim)
Model constructor that takes various parameters.
void SetMd2 (bool check)
Function that will set the model to MD2 is the boolean provided is true, otherwise it will assign the model to be an FBX.
void LoadModel (std::string const &path, Renderer *gameRenderer, std::string pathTexture)
Function responible for loading the model.
void Render (View lens, Shader &shader, glm::vec3 pos, glm::vec3 rot, float scale, bool rotate, float time, float direction, Renderer *gameRenderer, bool p)
makes use of the view information and graphics renderer among other things to render the model
void SetState (Md2Commands cmd)
sets the animation state of the model to the command provided as parameter
Md2State GetState () const
gets and returns the current Md2State of the Model
Mesh * GetMesh (int i)
gets and returns a pointer to the Mesh of the Model
Detailed Description
Holds the model information of objects, can be md2 or Fbx models.
Author
Christopher Logan
Version
01
Date
25/04/2021
Definition at line 38 of file Model.h.
Constructor & Destructor Documentation
Model() [1/2]
Model::Model (std::string const & path, Renderer * r, bool check) [inline]
Model constructor that takes various parameters.
Parameters
path - represents the path to the model
r - a pointer to the renderer
check - a boolean variable that checks if the model is MD2 or FBX
Definition at line 56 of file Model.h.
    {
        SetMd2(check);
        LoadModel(path, r, "");
        animations = true;
    }
Model() [2/2]
Model::Model (std::string const & path, Renderer * r, bool check, std::string pathTexture, bool anim) [inline]
Model constructor that takes various parameters.
Parameters
path - represents the path to the model
r - a pointer to the renderer
check - a boolean variable that checks if the model is MD2 or FBX
pathTexture - a string representing the path to the model texture @bool anim - a boolean flag indicating whether or not animations are true or false
Definition at line 73 of file Model.h.
    {
        SetMd2(check);
        LoadModel(path, r, pathTexture);
        animations = anim;
    }
Referenced by Enemy::Enemy(), and Player::Player().
Member Function Documentation
GetMesh()
Mesh* Model::GetMesh (int i) [inline]
gets and returns a pointer to the Mesh of the Model
Returns
Mesh*
Definition at line 140 of file Model.h.
{ return &fbxModel.meshes[i]; }
Referenced by GameAssetFactory::GetGameObject(), and GameAssetFactory::GetGameObjectSave().
GetState()
Md2State Model::GetState () const [inline]
gets and returns the current Md2State of the Model
Returns
Md2State
Definition at line 134 of file Model.h.
{ return currentState; }
LoadModel()
void Model::LoadModel (std::string const & path, Renderer * gameRenderer, std::string pathTexture)
Function responible for loading the model.
Parameters
path - represents the filepath to the model
gameRenderer - represents a pointer to the gameRenderer
pathTexture - a string that represents the path to the models texture
Definition at line 3 of file Model.cpp.
{
    if (fbx)
    {
        Fbx temp(path, gameRenderer);
        fbxModel = temp;
    }
    else if (md2)
    {
        md2Model.LoadModel(path.c_str(), pathTexture.c_str(), "./res/shader/md2vert.vert", "./res/shader/md2frag.frag", gameRenderer);
        currentState = md2Model.StartAnimation(WALK);
    }
}
References Fbx::Fbx().
Render()
void Model::Render (View lens, Shader & shader, glm::vec3 pos, glm::vec3 rot, float scale, bool rotate, float time, float direction, Renderer * gameRenderer, bool p)
makes use of the view information and graphics renderer among other things to render the model
Parameters
lens - holds the information that allows you to project and view the model
shader - represents the shader object used by the model
pos - the vec3 position of the model
rot - rotation vector of the model
scale - scale of the object
rotate - bool value confirming whether or not the model rotates
time - represents deltatime, which is the difference between the previous frame and the current frame
direction - the direction of the model
gameRenderer - a pointer to the renderer which is used to render the enemy model
p - represents if player exists or not
Definition at line 17 of file Model.cpp.
{
    if (fbx)
    {
        gameRenderer->SetShader(shader, lens);
        for (int i = 0; i < fbxModel.meshes.size(); i++)
        {
            gameRenderer->RenderModel(shader, GenerateMatFour(pos, rot, scale, rotate) * fbxModel.meshes[i].transform, fbxModel.meshes[i]);
        }
    }
    else if (md2)
    {
        if (animations)
        {
            rot.x = 180.695f;
            if(p)
                md2Model.RenderModel(&currentState, lens.GetProjection(), lens.GetView(), GenerateMatFour(pos, rot, scale, rotate), direction, gameRenderer);
            else
                md2Model.RenderModel(&currentState, lens.GetProjection(), lens.GetView(), pos, rot, direction, gameRenderer);
            md2Model.UpdateAnimation(&currentState, time, gameRenderer);
        }
        else
        {
            md2Model.RenderModel(NULL, lens.GetProjection(), lens.GetView(), GenerateMatFour(pos, rot, scale, rotate), 0, gameRenderer);
        }
    }
}
References Renderer::SetShader().
SetMd2()
void Model::SetMd2 (bool check) [inline]
Function that will set the model to MD2 is the boolean provided is true, otherwise it will assign the model to be an FBX.
Parameters
check - represents the check to see if the model is MD2 or not
Definition at line 85 of file Model.h.
                            {
        if (check)
        {
            md2 = true;
            fbx = false;
        }
        else
        {
            md2 = false;
            fbx = true;
        }
    }
SetState()
void Model::SetState (Md2Commands cmd) [inline]
sets the animation state of the model to the command provided as parameter
Parameters
cmd - represents the animation state that the function will provide the start animation function
Definition at line 128 of file Model.h.
{ currentState = md2Model.StartAnimation(cmd); }
Referenced by Enemy::SetState(), and Player::SetState().
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Model.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Model.cpp