Scene Class Reference
Contains the aspects of a game that would be held in a scene, this being gameObjects, Terrain, Skybox.
#include <Scene.h>
Public Member Functions
Scene ()
Default constructor.
Scene (std::string name, Renderer *render)
Name and Renderer constructor.
~Scene ()
Destructor.
void Run (View lens, float time, bool exit)
Runs the scene, setting up objects for rendering and changes.
void Init ()
Initilises the scene, setting up the terrain and skybox.
void Load (std::string file)
Loads the scene.
bool LoadSaveFile ()
Saves the save file.
float Lerp (float a, float b, float t)
Lerps the positions for terrain walking.
float Interpolate (float a, float b, float blend)
Interlopes personions for terrain walking.
void Unload ()
Unloads the scene.
std::string GetSceneName () const
Gets the name of the current scene.
void MakeGameObject (std::string t, std::string script, float scale, float x, float y, float z)
Function that uses the game asset factory to create a new game object.
GameObject * GetGameObject (int i)
Gets a gameobject from the game objects.
void UpdatePlayer (glm::vec3 position, glm::vec3 rotation, float time)
Updates the players position in relation to the world.
int GetPlayerIndice ()
Gets the playerInd value and returns it.
void FindPlayerIndice ()
Finds the playerInd value within the Scenes gameObjects.
glm::vec3 CheckSceneCollision (glm::vec3 pos)
Checks the players position against scene game objects for collisions.
Terrain * GetSceneTerrain ()
Returns the scenes terrain data.
glm::vec3 WorldToTerrainPosition (glm::vec3 p, bool average)
Converts a given world vec3 to terrain position for height/Y calculations.
glm::vec3 PlayerToTerrainPosition (glm::vec3 p, glm::vec3 terrainPosMovement)
Converts the players position into terrain position.
float Remap (float value, float oldMin, float oldMax, float newMin, float newMax)
Remaps a value from one range to another.
float BilinearInterpolation (glm::vec3 p)
Uses biliniear interpolation to output a new position.
ExitScreen GetExitScreen ()
void SetExitScreen (ExitScreen screen)
void MoveObjectAwayFromPlayer ()
moves all objects away from the player if they spawn to close to the player
void RunPlayer (View lens, float time, bool exit)
Runs the players information.
void UpdateGameObject (glm::vec3 position, int i, float time)
Updates the players game object.
glm::vec3 EnemyObstacleAvoidance (GameObject *self, glm::vec3 newPosition)
Obstacle avoidance for the enemies.
void FireWeapon (glm::vec3 weaponStartPos, glm::vec3 forward, float fireDistance)
Shoots the gun.
void EnemyFireWeapon (GameObject *enemy, float fireDistance)
Initilises the scene, setting up the terrain and skybox.
void SetPlayerWeapon (Weapon w)
Sets the players weapon.
Weapon GetPlayerWeapon ()
returns the players weapon
void SaveGame ()
Saves the game.
Static Public Member Functions
static bool intersectRaySegmentSphere (glm::vec3 o, glm::vec3 d, glm::vec3 so, float radius, glm::vec3 &ip)
Public Attributes
bool loaded
Detailed Description
Contains the aspects of a game that would be held in a scene, this being gameObjects, Terrain, Skybox.
Designed so many scenes can be made and run throught the game, allowing for a terrain and skybox, and many different gameobjects
Author
Christoper Logan
Version
01
Date
29/03/2021 Christopher Logan, Started
Author
Bryce Standley
Version
02
Date
06/04/2021 Bryce Standley, Ammended
Definition at line 40 of file Scene.h.
Constructor & Destructor Documentation
Scene()
Scene::Scene (std::string name, Renderer * render)
Name and Renderer constructor.
Parameters
The name of the scene
The renderer pointer
Definition at line 2 of file Scene.cpp.
{
    this->sceneName = name;
    gameRenderer = render;
    loaded = false;
    Init();
}
Member Function Documentation
BilinearInterpolation()
float Scene::BilinearInterpolation (glm::vec3 p)
Uses biliniear interpolation to output a new position.
Parameters
p
Returns
Definition at line 352 of file Scene.cpp.
{
    int intX = p.x;
    int intZ = p.z;
    float fracX = p.x - intX;
    float fracZ = p.z - intZ;
    float v1 = PlayerToTerrainPosition(glm::vec3(intX, 0, intZ), glm::vec3(0,0,0)).y;
    float v2 = PlayerToTerrainPosition(glm::vec3(intX, 0, intZ), glm::vec3(1,0,0)).y;
    float v3 = PlayerToTerrainPosition(glm::vec3(intX, 0, intZ + 1), glm::vec3(0,0,1)).y;
    float v4 = PlayerToTerrainPosition(glm::vec3(intX, 0, intZ), glm::vec3(1,0,1)).y;
    float i1 = Interpolate(v1, v2, fracX);
    float i2 = Interpolate(v3, v4, fracX);
    float newHeight = Interpolate(i1, i2, fracZ);
    return newHeight;
}
CheckSceneCollision()
glm::vec3 Scene::CheckSceneCollision (glm::vec3 pos)
Checks the players position against scene game objects for collisions.
Parameters
pos - current position the player has moved to
Returns
vec3 - new position if player collides with a object
Definition at line 581 of file Scene.cpp.
{
    glm::vec3 player = gameObjects[playerInd]->GetPos();
    glm::vec3 playerSphereOrigin(pos.x, pos.y - 0.75f, pos.z);
    float playerSphereRadius = 2.0f;
    int numberOfCollisions = 0;
    glm::vec3 shiftDelta = glm::vec3(0,0,0);
    std::vector<GameObject *> gameObjectsToRemoveFromScene;
    for (auto& go : gameObjects)
    {
        //Skip the player, we dont want collisions between the player and the player
        if (go->GetTag() == BoundingBox::PLAYER) continue;
        float distance = glm::distance(playerSphereOrigin, go->GetPos());
        if (go->GetTag() == BoundingBox::TOKEN && distance < playerSphereRadius)
        {
            if(Debugger::GetInstance()->debugCollisionsToConsole) std::cout << "Scene.cpp::INFO::Token GameObject - " << go->GetName() << " Hit" << std::endl;
            go->Kill();
            gameObjectsToRemoveFromScene.emplace_back(go);
            continue;
        }
        if (go->GetTag() == BoundingBox::STATIC_OBJECT && distance < playerSphereRadius || go->GetTag() == BoundingBox::ENEMY && distance < playerSphereRadius)
        {
            if (Debugger::GetInstance()->debugCollisionsToConsole) std::cout << "Scene.cpp::INFO::Static GameObject - " + go->GetName() + " hit" << std::endl;
            //Simple Collisions/distance checking, More complex collision detection is work in progress
            glm::vec3 dir = go->GetPos() - playerSphereOrigin;
            //the player is too close to a object and will be stopped
            pos.x = player.x;
            pos.y = player.y;
            pos.z = player.z;
        }
    
        /*//Get the information about the bounding box of a gameobject
        BoundingBox box = go->GetBoundingBox();
        std::vector<glm::vec3> vertex = box.GetVertexData();
        std::vector<int> index = box.GetIndiceData();
        std::vector<glm::vec3> normal = box.GetNormalData();
        int numberOfTriangles = (int)index.size()/3;
        for(int i = 0; i < numberOfTriangles; i++)
        {
            bool outsidePlane = false;
            bool outsideAllVerts = false;
            bool outsideAllEdges = false;
            //find points
            glm::vec3 a = vertex[i];
            glm::vec3 b = vertex[i+1];
            glm::vec3 c = vertex[i+2];
            //find vectors between points
            glm::vec3 ab = b - a;
            glm::vec3 ac = c - a;
            glm::vec3 bc = c - b;
            //find normal of the required triangle
            glm::vec3 pN = glm::cross(ab, ac);
            //check the normal is horizontal to the player
            if(pN.y > 0.1f) continue;
            //Find the sphere to plane distance
            float d = glm::dot(-((a + b + c) / 3.0f), pN);
            float ppd = glm::dot(pN, playerSphereOrigin) + d;//add square root if d isnt normalized
            //player Shphere is outside the triangles plane
            if(ppd > playerSphereRadius) {outsidePlane = true; continue;}
            bool outsideA = pow(glm::distance(a, playerSphereOrigin), 2) > pow(playerSphereRadius, 2);
            bool outsideB = pow(glm::distance(b, playerSphereOrigin), 2) > pow(playerSphereRadius,2);
            bool outsideC = pow(glm::distance(c, playerSphereOrigin), 2) > pow(playerSphereRadius,2);
            //sphere is outside of the triangle points
            if(outsideA && outsideB && outsideC) outsideAllVerts = true;
            glm::vec3 ip;
            if(!intersectRaySegmentSphere(a, ab, playerSphereOrigin, pow(playerSphereRadius,2), ip) &&
                !intersectRaySegmentSphere(b, ac, playerSphereOrigin, pow(playerSphereRadius,2), ip) &&
                !intersectRaySegmentSphere(c, bc, playerSphereOrigin, pow(playerSphereRadius,2), ip)) outsideAllEdges = true;
            if(outsideAllEdges && outsideAllVerts) continue;
            numberOfCollisions++;
            shiftDelta += pN * (playerSphereRadius - ppd);
        }
         */
    }
    std::vector<GameObject*>::iterator removed;
    for(auto &go : gameObjectsToRemoveFromScene)
    {
        //if(Debugger::GetInstance()->debugCollisionsToConsole) std::cout << "Scene.cpp::INFO::GameObject - " + go->GetName() +" hit and removed from scene" << std::endl;
        removed = std::remove(gameObjects.begin(), gameObjects.end(), go);
        gameObjects.erase(removed);
    }
    /*if(numberOfCollisions != 0)
    {
        shiftDelta /= numberOfCollisions;
        glm::normalize(shiftDelta);
        pos += shiftDelta;
    }*/
    return pos;
}
GetGameObject()
GameObject* Scene::GetGameObject (int i) [inline]
Gets a gameobject from the game objects.
Parameters
i - The indice of the game object
Definition at line 125 of file Scene.h.
{ return gameObjects[i]; }
GetSceneName()
std::string Scene::GetSceneName () const [inline]
Gets the name of the current scene.
Returns
string
Definition at line 103 of file Scene.h.
{ return sceneName; }
GetSceneTerrain()
Terrain* Scene::GetSceneTerrain () [inline]
Returns the scenes terrain data.
Returns
terrain
Definition at line 165 of file Scene.h.
{return gameTerrain;}
intersectRaySegmentSphere()
bool Scene::intersectRaySegmentSphere (glm::vec3 o, glm::vec3 d, glm::vec3 so, float radius, glm::vec3 & ip) [static]
Parameters
o
d
so
radius
ip
Returns
bool
Definition at line 697 of file Scene.cpp.
{
    //we pass in d non-normalized to keep it's length
    //then we use that length later to compare the intersection point to make sure
    //we're within the actual ray segment
    auto l = (float)sqrt(pow(d.x,2) + pow(d.y, 2) + pow(d.z, 2));
    d /= l;
    glm::vec3 m = o - so;
    float b = glm::dot(m, d);
    float c = glm::dot(m, m) - radius;
    // Exit if r’s origin outside s (c > 0) and r pointing away from s (b > 0)
    if(c > 0.0f && b > 0.0f)
        return false;
    float discr = b*b - c;
    // A negative discriminant corresponds to ray missing sphere
    if(discr < 0.0f)
        return false;
    // Ray now found to intersect sphere, compute smallest t value of intersection
    float t = -b - sqrtf(discr);
    // If t is negative, ray started inside sphere so clamp t to zero
    if(t < 0.0f)
        t = 0.0f;
    ip = o + (d * t);
    //here's that last segment check I was talking about
    if(t > l)
        return false;
    return true;
}
MakeGameObject()
void Scene::MakeGameObject (std::string t, std::string script, float scale, float x, float y, float z)
Function that uses the game asset factory to create a new game object.
Parameters
t - the type of game object it is
n - Name of the object
modalName - the file path to load in the model
shaderV - The vertex shader file path
shaderF - The fragment shader file path
scale - The scale of the object
x - The x positon of the object
y - The y position of the object
z - The z position of the object
rotate - Sets if the model needs to be rotated on entry
speed - The speed at which it moves
Definition at line 411 of file Scene.cpp.
{
    //Check the terrain height to make sure the object isn't under the terrain;
    y += WorldToTerrainPosition(glm::vec3(x,y,z), false).y;
    GameObject* newGameObject = factory->GetGameObject(t, script, scale, glm::vec3(x, y, z));
    if (newGameObject != nullptr)
    {
        gameObjects.push_back(newGameObject);
        if(t == "water") { waterIndex = (int)gameObjects.size() - 1;}
    }
    else
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "Scene.cpp::ERROR::GAME_ASSET_FACTORY::TYPE_UNKNOWN" << std::endl;
    }
}
PlayerToTerrainPosition()
glm::vec3 Scene::PlayerToTerrainPosition (glm::vec3 p, glm::vec3 terrainPosMovement)
Converts the players position into terrain position.
Parameters
p - players position
terrainPosMovement - How much to check on each axis. p.x + 1 doesnt map to the same as terrainX + 1
Returns
Definition at line 741 of file Scene.cpp.
{
    float worldx, worldy, worldz;
    worldx = Remap(p.x, 0, 52.0f * gameTerrain->GetScales().x, 0, (float)gameTerrain->getSize() - 1);
    worldz = Remap(p.z, 0, 52.0f * gameTerrain->GetScales().z, 0, (float)gameTerrain->getSize() - 1);
    worldy = gameTerrain->GetVertexHeight(worldx + terrainPosMovement.x , worldz + terrainPosMovement.z);
    return glm::vec3(worldx, worldy, worldz);
}
Remap()
float Scene::Remap (float value, float oldMin, float oldMax, float newMin, float newMax)
Remaps a value from one range to another.
Parameters
value - value to remap
oldMin - old min value
oldMax - old max value
newMin - new min value
newMax - new max value
Returns
output - new value in the same range of the old values but within the new values
Definition at line 735 of file Scene.cpp.
{
    float out = newMin + (newMax - newMin) * ((value - oldMin) / (oldMax - oldMin));
    return out;
}
Run()
void Scene::Run (View lens, float time, bool exit)
Runs the scene, setting up objects for rendering and changes.
Parameters
lens - Holds information to do with the position of the camera, projects and views
Definition at line 151 of file Scene.cpp.
{
    if (exitScreen.exitScreenDisplay)
    {
        endScreenGUI->Draw();
    }
    else if(!mainMenuGui->displayMainMenu && !mainMenuGui->displayPauseMenu && !mainMenuGui->displaySettings && !mainMenuGui->displayDifficulty && !mainMenuGui->displayControls)
    {
        singleton<Manager>::getInstance().Update(time);
        singleton<Manager>::getInstance().UpdateWeapon(time);
        singleton<Manager>::getInstance().UpdateEnemyDeath(time);
        gameRenderer->BindTexture(gameTerrain->GetTextIds());
        Shader t = gameTerrain->GetShader();
        gameRenderer->SetShaderTerrain(t, lens);
        gameTerrain->SetShader(t);
        gameRenderer->RenderTerrain(gameTerrain->GetVAO(), gameTerrain->GetIndicesSize());
        //Skybox
        gameRenderer->SetShaderSkybox(gameSkybox->skyShader, lens);
        gameRenderer->RenderSkybox(gameSkybox->VAO, gameSkybox->texture);
        std::vector<GameObject*> gameObjectsToRemoveFromScene;
        //Models
        for (int x = 0; x < gameObjects.size(); x++)
        {
            gameObjects[x]->Update(time);
            if (x != playerInd)
            {
                gameObjects[x]->Render(lens, time, gameRenderer);
                if (gameObjects[x]->GetType() == "enemy")
                {
                    auto* e = (Enemy*)gameObjects[x];
                    UpdateGameObject(e->GetPos(), x, time);
                    if(e->GetFireWeapon()) { EnemyFireWeapon(e, 5); }
                    if (!gameObjects[x]->Kill())
                    {
                        gameObjectsToRemoveFromScene.emplace_back(gameObjects[x]);
                    }
                }
            }
        }
        std::vector<GameObject*>::iterator removed;
            for (auto& go : gameObjectsToRemoveFromScene)
            {
                //if(Debugger::GetInstance()->debugCollisionsToConsole) std::cout << "Scene.cpp::INFO::GameObject - " + go->GetName() +" hit and removed from scene" << std::endl;
                glm::vec3 pp = gameObjects[playerInd]->GetPos();
                int chosenOne = 0;
                float distance = 0;
                for (int i = 0; i < spawnPoints.size(); i++)
                {
                    float newDistance = glm::distance(pp, spawnPoints[i]);
                    if (newDistance > distance)
                    {
                        distance = newDistance;
                        chosenOne = i;
                    }
                }
                auto* e = (Enemy*)go;
                e->ResetEnemy(spawnPoints[chosenOne]);
                //Spawn New GameObject
            }
        if(singleton<Manager>::getInstance().enemyDeathTimer <= 0 && singleton<Manager>::getInstance().hasKills)
        {
            for(auto* go : gameObjects)
            {
                if(go->GetTag() == BoundingBox::ENEMY)
                {
                    auto* e = (Enemy*)go;
                    //e->SetKillFSM(true);
                }
            }
        }
        //if the player is firing, fire the weapon duh
        if (playerWeapon.firingWeapon && playerWeapon.canFireWeapon && singleton<Manager>::getInstance().weaponTimer <= 0)
        {
            playerWeapon.firingWeapon = false;
            singleton<Manager>::getInstance().weaponTimer = 5.0f / 17.0f;
            singleton<Manager>::getInstance().fireWeapon = false;
            playerWeapon.canFireWeapon = false;
            auto* p = (Player*)gameObjects[playerInd];
            p->FireWeapon();
            FireWeapon(gameObjects[playerInd]->GetPos(), lens.GetForward(), 15.0f);
        }
        
        //if the timer is 0 and we can fire again
        if (singleton<Manager>::getInstance().weaponTimer <= 0)
        {
            auto* p = (Player*)gameObjects[playerInd];
            p->BackToIdle();
            playerWeapon.canFireWeapon = true;
        }
        //If game object is of type player
        UpdatePlayer(lens.GetPosition(), lens.GetRotation(), time);
        //GameUI
        if (gameGui)
        {
            auto* p = (Player*)gameObjects[playerInd];
            gameGui->terrainHeight = PlayerToTerrainPosition(p->GetPos(), glm::vec3(0,0,0)).y;
            gameGui->Draw(p);
        }
    }
    else
    {
        mainMenuGui->Draw();
    }
}
References MainMenuGUI::Draw(), EndScreenGUI::Draw(), Renderer::RenderSkybox(), Renderer::SetShaderSkybox(), Renderer::SetShaderTerrain(), and Skybox::skyShader.
UpdatePlayer()
void Scene::UpdatePlayer (glm::vec3 position, glm::vec3 rotation, float time)
Updates the players position in relation to the world.
Parameters
position - The position of the camera
Definition at line 298 of file Scene.cpp.
{
    if(playerStartPosition == glm::vec3(-1000,-1000, -1000)) { playerStartPosition = position;}
    if(position == gameObjects[playerInd]->GetPos()) return;
    glm::vec3 newPos = WorldToTerrainPosition(position, false);
    newPos.y += Lerp(1.5f, 3.0f, time * 4.0f);
    //newPos.y = Lerp(newPos.y + 2.0f, newPos.y + 3.0f, time * 2.0f);
    //newPos.y = BilinearInterpolation(position);
    if (newPos.y >= 25.0f && !Debugger::GetInstance()->noPlayerYClip)
    {
        newPos.x = gameObjects[playerInd]->GetPos().x;
        newPos.y = gameObjects[playerInd]->GetPos().y;
        newPos.z = gameObjects[playerInd]->GetPos().z;
    }
    
   /* if (newPos.y < WorldToTerrainPosition(newPos, false).y + 1.0f)
    {
        newPos.y = WorldToTerrainPosition(newPos, false).y + 2.0f;
    }
    */
    newPos = CheckSceneCollision(newPos);
    gameObjects[playerInd]->SetPos(newPos);
    //std::cout << "Player to water distance: " << glm::distance(newPos, gameObjects[waterIndex]->GetPos()) << std::endl;
    if(glm::distance(newPos, gameObjects[waterIndex]->GetPos()) < 15.0f)
    {
        //take 10 health from the player if they get to close to the water
        Player* p = (Player*)gameObjects[playerInd];
        p->setHealth(p->getHealth() - 10);
        if (p->getHealth() <= 0)
        {
            p->setHealth(0);
            // tell the player to die
            gameGui->DisplayDeathScreen();
        }
    }
}
WorldToTerrainPosition()
glm::vec3 Scene::WorldToTerrainPosition (glm::vec3 p, bool average)
Converts a given world vec3 to terrain position for height/Y calculations.
Returns
vec3 - position relative to the terrain
Definition at line 370 of file Scene.cpp.
{
    //std::cout << "Updaing position" << Debugger::GetInstance()->DebugVec3(p) << std::endl;
    float worldx, worldz;
    worldx = Remap(p.x, 0, 52.0f * gameTerrain->GetScales().x, 0, (float)gameTerrain->getSize());
    worldz = Remap(p.z, 0, 52.0f * gameTerrain->GetScales().z, 0, (float)gameTerrain->getSize());
    if(average)
    {
        float y = (gameTerrain->getAverageHeight((int)worldx, (int)worldz));
        y = Remap(y, gameTerrain->GetMinHeight().y, gameTerrain->GetMaxHeight().y, 2, 80.0f);
        p.y = y;
    }
    else
    {
        //p.y = (gameTerrain->GetVertexHeight((int)worldx, (int)worldz) / (worldToTerrainScaleFactor * gameTerrain->GetScales().y));
        float y = gameTerrain->GetVertexHeight((int)worldx, (int)worldz);
        p.y = Remap(y, gameTerrain->GetMinHeight().y, gameTerrain->GetMaxHeight().y, 2, 80.0f);
    }
    return p;
}
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Scene.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Scene.cpp