Shader Class Reference
A class that is responsible for shaders, allowing you to open/use shaders and set uniforms of various types for use in the shaders.
#include <Shader.h>
Public Member Functions
Shader ()
default constructor
Shader (const char *vertexPath, const char *fragmentPath, const char *geometryPath=nullptr)
A constructor that takes in paths to the shaders and generates them.
void use ()
Allows you to activate and use the shader
void setBool (const std::string &name, bool value) const
sets a boolean for use in the shader program
void setInt (const std::string &name, int value) const
sets an integer for use in the shader program
void setFloat (const std::string &name, float value) const
sets a float for use in the shader program
void setVec2 (const std::string &name, const glm::vec2 &value) const
sets a vec2 for use in the shader program
void setVec2 (const std::string &name, float x, float y) const
sets a vec2 for use in the shader program (Overloaded to allow two floats to define the vec2)
void setVec3 (const std::string &name, const glm::vec3 &value) const
sets a vec3 for use in the shader program
void setVec3 (const std::string &name, float x, float y, float z) const
sets a vec3 for use in the shader program (Overloaded to allow three floats to define the vec3)
void setVec4 (const std::string &name, const glm::vec4 &value) const
sets a vec4 for use in the shader program
void setVec4 (const std::string &name, float x, float y, float z, float w)
sets a vec4 for use in the shader program (Overloaded to allow four floats to define the vec4)
void setMat2 (const std::string &name, const glm::mat2 &mat) const
sets a mat2 for use in the shader program
void setMat3 (const std::string &name, const glm::mat3 &mat) const
sets a mat3 for use in the shader program
void setMat4 (const std::string &name, const glm::mat4 &mat) const
sets a mat4 for use in the shader program
Public Attributes
unsigned int ID
shader ID
Detailed Description
A class that is responsible for shaders, allowing you to open/use shaders and set uniforms of various types for use in the shaders.
Author
Dylan Blereau
Version
01
Date
01/03/2021 Dylan Blereau, Started
Definition at line 24 of file Shader.h.
Constructor & Destructor Documentation
Shader()
Shader::Shader (const char * vertexPath, const char * fragmentPath, const char * geometryPath = nullptr)
A constructor that takes in paths to the shaders and generates them.
Parameters
vertexPath - represents the path to the vertex shader
fragmentPath - represents the path to the fragment shader
geometryPath - represents the path to the geometry shader (set to null in this case)
retrieve the vertex/fragment source code from filePath
ensure ifstream objects can throw exceptions:
open files
read file's buffer contents into streams
close file handlers
convert stream into string
if geometry shader path is present, also load a geometry shader
vertex shader
fragment Shader
if geometry shader is given, compile geometry shader
shader Program
delete the shaders as they're linked into our program now and no longer necessery
Definition at line 3 of file Shader.cpp.
{
    std::string vertexCode;
    std::string fragmentCode;
    std::string geometryCode;
    std::ifstream vShaderFile;
    std::ifstream fShaderFile;
    std::ifstream gShaderFile;
    vShaderFile.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    fShaderFile.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    gShaderFile.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    try
    {
        vShaderFile.open(vertexPath);
        fShaderFile.open(fragmentPath);
        std::stringstream vShaderStream, fShaderStream;
        vShaderStream << vShaderFile.rdbuf();
        fShaderStream << fShaderFile.rdbuf();
        vShaderFile.close();
        fShaderFile.close();
        vertexCode = vShaderStream.str();
        fragmentCode = fShaderStream.str();
        if (geometryPath != nullptr)
        {
            gShaderFile.open(geometryPath);
            std::stringstream gShaderStream;
            gShaderStream << gShaderFile.rdbuf();
            gShaderFile.close();
            geometryCode = gShaderStream.str();
        }
    }
    catch (std::ifstream::failure& e)
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "Shader.cpp::ERROR::SHADER::FILE_NOT_SUCCESFULLY_READ" << std::endl;
    }
    const char* vShaderCode = vertexCode.c_str();
    const char* fShaderCode = fragmentCode.c_str();
    unsigned int vertex, fragment;
    vertex = glCreateShader(GL_VERTEX_SHADER);
    glShaderSource(vertex, 1, &vShaderCode, NULL);
    glCompileShader(vertex);
    checkCompileErrors(vertex, "VERTEX");
    fragment = glCreateShader(GL_FRAGMENT_SHADER);
    glShaderSource(fragment, 1, &fShaderCode, NULL);
    glCompileShader(fragment);
    checkCompileErrors(fragment, "FRAGMENT");
    unsigned int geometry;
    if (geometryPath != nullptr)
    {
        const char* gShaderCode = geometryCode.c_str();
        geometry = glCreateShader(GL_GEOMETRY_SHADER);
        glShaderSource(geometry, 1, &gShaderCode, NULL);
        glCompileShader(geometry);
        checkCompileErrors(geometry, "GEOMETRY");
    }
    ID = glCreateProgram();
    glAttachShader(ID, vertex);
    glAttachShader(ID, fragment);
    if (geometryPath != nullptr)
        glAttachShader(ID, geometry);
    glLinkProgram(ID);
    checkCompileErrors(ID, "PROGRAM");
    glDeleteShader(vertex);
    glDeleteShader(fragment);
    if (geometryPath != nullptr)
        glDeleteShader(geometry);
}
Referenced by Enemy::Enemy(), Md2::LoadModel(), Terrain::luaLoader(), and Player::Player().
Member Function Documentation
setBool()
void Shader::setBool (const std::string & name, bool value) const
sets a boolean for use in the shader program
Parameters
name - represents the name of the variable
value - represents the variable value
Definition at line 93 of file Shader.cpp.
{
    glUniform1i(glGetUniformLocation(ID, name.c_str()), (int)value);
}
setFloat()
void Shader::setFloat (const std::string & name, float value) const
sets a float for use in the shader program
Parameters
name - represents the name of the variable
value - represents the variable value
Definition at line 105 of file Shader.cpp.
{
    glUniform1f(glGetUniformLocation(ID, name.c_str()), value);
}
setInt()
void Shader::setInt (const std::string & name, int value) const
sets an integer for use in the shader program
Parameters
name - represents the name of the variable
value - represents the variable value
Definition at line 99 of file Shader.cpp.
{
    glUniform1i(glGetUniformLocation(ID, name.c_str()), value);
}
Referenced by Terrain::setTextures(), and OpenGL::SkyboxSetup().
setMat2()
void Shader::setMat2 (const std::string & name, const glm::mat2 & mat) const
sets a mat2 for use in the shader program
Parameters
name - represents the name of the variable
mat - represents the variable value
Definition at line 147 of file Shader.cpp.
{
    glUniformMatrix2fv(glGetUniformLocation(ID, name.c_str()), 1, GL_FALSE, &mat[0][0]);
}
setMat3()
void Shader::setMat3 (const std::string & name, const glm::mat3 & mat) const
sets a mat3 for use in the shader program
Parameters
name - represents the name of the variable
mat - represents the variable value
Definition at line 153 of file Shader.cpp.
{
    glUniformMatrix3fv(glGetUniformLocation(ID, name.c_str()), 1, GL_FALSE, &mat[0][0]);
}
setMat4()
void Shader::setMat4 (const std::string & name, const glm::mat4 & mat) const
sets a mat4 for use in the shader program
Parameters
name - represents the name of the variable
mat - represents the variable value
Definition at line 159 of file Shader.cpp.
{
    glUniformMatrix4fv(glGetUniformLocation(ID, name.c_str()), 1, GL_FALSE, &mat[0][0]);
}
setVec2() [1/2]
void Shader::setVec2 (const std::string & name, const glm::vec2 & value) const
sets a vec2 for use in the shader program
Parameters
name - represents the name of the variable
value - represents the variable value
Definition at line 111 of file Shader.cpp.
{
    glUniform2fv(glGetUniformLocation(ID, name.c_str()), 1, &value[0]);
}
setVec2() [2/2]
void Shader::setVec2 (const std::string & name, float x, float y) const
sets a vec2 for use in the shader program (Overloaded to allow two floats to define the vec2)
Parameters
name - represents the name of the variable
x - sets the x value
y - sets the y value
Definition at line 117 of file Shader.cpp.
{
    glUniform2f(glGetUniformLocation(ID, name.c_str()), x, y);
}
setVec3() [1/2]
void Shader::setVec3 (const std::string & name, const glm::vec3 & value) const
sets a vec3 for use in the shader program
Parameters
name - represents the name of the variable
value - represents the variable value
Definition at line 123 of file Shader.cpp.
{
    glUniform3fv(glGetUniformLocation(ID, name.c_str()), 1, &value[0]);
}
setVec3() [2/2]
void Shader::setVec3 (const std::string & name, float x, float y, float z) const
sets a vec3 for use in the shader program (Overloaded to allow three floats to define the vec3)
Parameters
name - represents the name of the variable
x - sets the x value
y - sets the y value
z - sets the z value
Definition at line 129 of file Shader.cpp.
{
    glUniform3f(glGetUniformLocation(ID, name.c_str()), x, y, z);
}
Referenced by OpenGL::SetShaderTerrain().
setVec4() [1/2]
void Shader::setVec4 (const std::string & name, const glm::vec4 & value) const
sets a vec4 for use in the shader program
Parameters
name - represents the name of the variable
value - represents the variable value
Definition at line 135 of file Shader.cpp.
{
    glUniform4fv(glGetUniformLocation(ID, name.c_str()), 1, &value[0]);
}
setVec4() [2/2]
void Shader::setVec4 (const std::string & name, float x, float y, float z, float w)
sets a vec4 for use in the shader program (Overloaded to allow four floats to define the vec4)
Parameters
name - represents the name of the variable
x - sets the x value
y - sets the y value
z - sets the z value
w - sets the w value
Definition at line 141 of file Shader.cpp.
{
    glUniform4f(glGetUniformLocation(ID, name.c_str()), x, y, z, w);
}
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Shader.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Shader.cpp