GameAssetFactory Class Reference
Holds the information so that game objects can be made in the engine by taking in values that allow us to set the different types.
#include <GameAssetFactory.h>
Public Member Functions
GameAssetFactory (Renderer *r)
Game asset factory contructor with the renderer.
GameObject * GetGameObject (std::string t, std::string script, float scale, glm::vec3 position)
Creates the game object and returns it.
GameObject * GetGameObjectSave (std::string t, std::string script, float scale, glm::vec3 position, float health, float ammo, std::string state, int savedPoints, int savedTokens, int savedKills)
Creates the game object and returns it.
void ResetFactory ()
Detailed Description
Holds the information so that game objects can be made in the engine by taking in values that allow us to set the different types.
Author
Christopher Logan
Version
01
Date
3/04/2021
@bugs none to be seen
Definition at line 23 of file GameAssetFactory.h.
Constructor & Destructor Documentation
GameAssetFactory()
GameAssetFactory::GameAssetFactory (Renderer * r) [inline]
Game asset factory contructor with the renderer.
Parameters
r - The renderer for the game engine
Definition at line 31 of file GameAssetFactory.h.
{ renderer = r; playerMade = false; first = true; id = 0; }
Referenced by Scene::Init().
Member Function Documentation
GetGameObject()
GameObject * GameAssetFactory::GetGameObject (std::string t, std::string script, float scale, glm::vec3 position)
Creates the game object and returns it.
Parameters
t - The type of object it is, if it does not fit it will return nullptr
modelName - The model filepath
shaderV - The vertex shader
shaderF - the fragment shader
scale - The object scale
position - The inital position
speed - the speed of movement
Returns
GameObject*
Definition at line 3 of file GameAssetFactory.cpp.
{
    if(Debugger::GetInstance()->debugToConsole) std::cout << "script -> " << script << std::endl;
    if (type == "player" && !playerMade)
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "Player done" << std::endl;
        GameObject* obj = new Player(position, glm::vec3(0, 0, 0), scale, renderer, script);
        BoundingBox box = BoundingBox();
        //box = box.GenerateBoundingBox(obj->GetModel().GetMesh(0));
        //obj->SetBoundingBox(box);
        //obj->SetCollisionTag(BoundingBox::CollisionTag::PLAYER);
        playerMade = true;
        return obj;
    }
    else if (type == "static")
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "static done" << std::endl;
        GameObject* obj = new Static(position, glm::vec3(0, 0, 0), scale, renderer, script);
        BoundingBox box = BoundingBox();
        box = box.GenerateBoundingBox(obj->GetModel().GetMesh(0));
        obj->SetBoundingBox(box);
        obj->SetCollisionTag(BoundingBox::CollisionTag::STATIC_OBJECT);
        obj->SetName("StaticObject");
        obj->SetType("static");
        return obj;
    }
    else if (type == "enemy")
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "Enemy done" << std::endl;
        GameObject* obj = new Enemy(position, glm::vec3(0, 0, 0), renderer, script);
        obj->SetCollisionTag(BoundingBox::CollisionTag::ENEMY);
        obj->SetName("Enemy");
        obj->SetType("enemy");
        obj->SetId(id);
        id++;
        //if (first)
            //first = false;
        return obj;
    }
    else if (type == "token")
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "token done" << std::endl;
        GameObject* obj = new Token(position, glm::vec3(0, 0, 0), scale, renderer, script);
        obj->SetCollisionTag(BoundingBox::CollisionTag::TOKEN);
        obj->SetName("Token");
        obj->SetType("token");
        return obj;
    }
    else if(type == "water")
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "water done" << std::endl;
        GameObject* obj = new Water(position, glm::vec3(0, 0, 0), scale, renderer, script);
        obj->SetCollisionTag(BoundingBox::CollisionTag::WATER);
        obj->SetName("Water");
        obj->SetType("water");
        return obj;
    }
    else
        return nullptr;
}
References BoundingBox::BoundingBox(), BoundingBox::GenerateBoundingBox(), Model::GetMesh(), GameObject::GetModel(), GameObject::SetBoundingBox(), GameObject::SetCollisionTag(), GameObject::SetId(), GameObject::SetName(), and GameObject::SetType().
GetGameObjectSave()
GameObject * GameAssetFactory::GetGameObjectSave (std::string t, std::string script, float scale, glm::vec3 position, float health, float ammo, std::string state, int savedPoints, int savedTokens, int savedKills)
Creates the game object and returns it.
Parameters
t - The type of object it is, if it does not fit it will return nullptr
modelName - The model filepath
shaderV - The vertex shader
shaderF - the fragment shader
scale - The object scale
position - The inital position
speed - the speed of movement
Returns
GameObject*
Definition at line 65 of file GameAssetFactory.cpp.
{
    if(Debugger::GetInstance()->debugToConsole) std::cout << "script -> " << script << std::endl;
    if (type == "player" && !playerMade)
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "Player done" << std::endl;
        GameObject* obj = new Player(position, glm::vec3(0, 0, 0), scale, renderer, script, health, state, savedPoints, savedTokens, savedKills);
        BoundingBox box = BoundingBox();
        //box = box.GenerateBoundingBox(obj->GetModel().GetMesh(0));
        //obj->SetBoundingBox(box);
        //obj->SetCollisionTag(BoundingBox::CollisionTag::PLAYER);
        playerMade = true;
        return obj;
    }
    else if (type == "static")
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "static done" << std::endl;
        GameObject* obj = new Static(position, glm::vec3(0, 0, 0), scale, renderer, script);
        BoundingBox box = BoundingBox();
        box = box.GenerateBoundingBox(obj->GetModel().GetMesh(0));
        obj->SetBoundingBox(box);
        obj->SetCollisionTag(BoundingBox::CollisionTag::STATIC_OBJECT);
        obj->SetName("StaticObject");
        obj->SetType("static");
        return obj;
    }
    else if (type == "enemy")
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "Enemy done" << std::endl;
        GameObject* obj = new Enemy(position, glm::vec3(0, 0, 0), scale, renderer, script, health, ammo, state);
        obj->SetCollisionTag(BoundingBox::CollisionTag::ENEMY);
        obj->SetName("Enemy");
        obj->SetType("enemy");
        obj->SetId(id);
        id++;
        if (first)
            first = false;
        return obj;
    }
    else if (type == "token")
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "token done" << std::endl;
        GameObject* obj = new Token(position, glm::vec3(0, 0, 0), scale, renderer, script);
        obj->SetCollisionTag(BoundingBox::CollisionTag::TOKEN);
        obj->SetName("Token");
        obj->SetType("token");
        return obj;
    }
    else if(type == "water")
    {
        if(Debugger::GetInstance()->debugToConsole) std::cout << "water done" << std::endl;
        GameObject* obj = new Water(position, glm::vec3(0, 0, 0), scale, renderer, script);
        obj->SetCollisionTag(BoundingBox::CollisionTag::WATER);
        obj->SetName("Water");
        obj->SetType("water");
        return obj;
    }
    else
        return nullptr;
}
References BoundingBox::BoundingBox(), BoundingBox::GenerateBoundingBox(), Model::GetMesh(), GameObject::GetModel(), GameObject::SetBoundingBox(), GameObject::SetCollisionTag(), GameObject::SetId(), GameObject::SetName(), and GameObject::SetType().
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/GameAssetFactory.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/GameAssetFactory.cpp