OpenGL Class Reference
The abstract OpenGL version of the renderer. Uses the Renderer parent class to have an abstract opengl class that doesnt directly intereact with the system and is used via facading it into the system.
#include <OpenGL.h>
Public Member Functions
virtual void RenderTerrain (unsigned int VAO, int size)
Renders the games terrain.
virtual void RenderModel (Shader &shader, glm::mat4 newModel, Mesh mesh)
Renders the games model.
virtual void BindTexture (std::vector< unsigned int > textures)
Binds textures to memory.
virtual void DepthTest ()
Calls the depth test.
virtual void RenderSkybox (unsigned int VAO, unsigned int texture)
Renders the sky box.
virtual void SetShader (Shader shader, View lens)
Sets the shader and uses it.
virtual void SetShaderSkybox (Shader shader, View lens)
Sets the shader and uses it for the skybox.
virtual void TerrainSetup (std::vector< glm::vec3 > totalData, std::vector< unsigned int > Indices, unsigned int &VAO, unsigned int &VBO, unsigned int &EBO)
Sets up the terrain data.
virtual void SkyboxSetup (std::vector< float > skyVerts, std::vector< std::string > faces, unsigned int &VAO, unsigned int &VBO, unsigned int &texture, Shader &skyShader)
Sets up the skybox.
virtual unsigned int TextureFromFile (std::string path, const std::string &directory)
grabs a texture from a specified file path
virtual void SetupMesh (unsigned int &VAO, unsigned int &VBO, unsigned int &EBO, std::vector< Vertex > vertices, std::vector< unsigned int > indices)
Sets an objects mesh.
virtual void SetShaderTerrain (Shader &shader, View lens)
Sets up the shader for the terrain.
virtual void RenderExitScreen (unsigned int VAO, unsigned int EBO, unsigned int texture)
Rends the exit model.
virtual void ExitScreenSetup (std::vector< glm::vec3 > vertexData, std::vector< unsigned int > indicesData, unsigned int &VAO, unsigned int &VBO, unsigned int &EBO)
Sets up the exit screen.
unsigned int TextureFromFile (std::string path)
virtual int LoadModel (int numFrames, std::vector< int > commands, unsigned int &VAO, v3 anorms[162], std::vector< std::vector< glm::vec3 >> vertices, std::vector< std::vector< int >> normals)
virtual void RenderModel (int number, Md2State *animState, glm::mat4 proj, glm::mat4 view, glm::mat4 genFour, float direction, unsigned int &VAO, unsigned int &textureId, Shader &shader)
virtual void RenderModel (int number, Md2State *animState, glm::mat4 proj, glm::mat4 view, glm::vec3 position, glm::vec3 rotation, float direction, unsigned int &VAO, unsigned int &textureId, Shader &shader)
GlfwWindow * GetGlfwWindow ()
void SetGlfwWindow (GlfwWindow *g)
Detailed Description
The abstract OpenGL version of the renderer. Uses the Renderer parent class to have an abstract opengl class that doesnt directly intereact with the system and is used via facading it into the system.
Author
Christoper Logan
Version
01
Date
15/03/2021 Christopher Logan, Started
Definition at line 26 of file OpenGL.h.
Member Function Documentation
BindTexture()
void OpenGL::BindTexture (std::vector< unsigned int > textures) [virtual]
Binds textures to memory.
Parameters
textures - The list of textures being used
Reimplemented from Renderer.
Definition at line 25 of file OpenGL.cpp.
{
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, textures[0]);
    glActiveTexture(GL_TEXTURE1);
    glBindTexture(GL_TEXTURE_2D, textures[1]);
    glActiveTexture(GL_TEXTURE2);
    glBindTexture(GL_TEXTURE_2D, textures[2]);
    glActiveTexture(GL_TEXTURE3);
    glBindTexture(GL_TEXTURE_2D, textures[3]);
    glActiveTexture(GL_TEXTURE4);
    glBindTexture(GL_TEXTURE_2D, textures[4]);
}
ExitScreenSetup()
void OpenGL::ExitScreenSetup (std::vector< glm::vec3 > vertexData, std::vector< unsigned int > indicesData, unsigned int & VAO, unsigned int & VBO, unsigned int & EBO) [virtual]
Sets up the exit screen.
Parameters
vertexData - the positions data
indices - The indices data
VAO - The vertex array object
VBO - The vertex buffer object
EBO - Another buffer
Reimplemented from Renderer.
Definition at line 122 of file OpenGL.cpp.
                                                                                                                                                    {
    glGenVertexArrays(1, &VAO);
    glGenBuffers(1, &VBO);
    glGenBuffers(1, &EBO);
    glBindVertexArray(VAO);
    glBindBuffer(GL_ARRAY_BUFFER, VBO);
    glBufferData(GL_ARRAY_BUFFER, vertexData.size() * sizeof(glm::vec3), &vertexData[0], GL_STATIC_DRAW);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), &indices[0], GL_STATIC_DRAW);
    //postion attributes
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 9 * sizeof(float), (void*)0);
    glEnableVertexAttribArray(0);
    //texture attributes
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 9 * sizeof(float), (void*)(3 * sizeof(float)));
    glEnableVertexAttribArray(1);
}
RenderExitScreen()
void OpenGL::RenderExitScreen (unsigned int VAO, unsigned int EBO, unsigned int texture) [virtual]
Rends the exit model.
Parameters
VAO - The vertex array object
texture - The texture number
EBO - Another buffer
Reimplemented from Renderer.
Definition at line 16 of file OpenGL.cpp.
                                                                                     {
    glBindVertexArray(VAO);
    glActiveTexture(GL_TEXTURE5);
    glBindTexture(GL_TEXTURE5, texture);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
    glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_INT, 0);
    glBindVertexArray(0);
}
RenderModel()
void OpenGL::RenderModel (Shader & shader, glm::mat4 newModel, Mesh mesh) [virtual]
Renders the games model.
Parameters
shader - The objects shader
newModel - The matrix4 model infromation for rotation or scaling
The mesh - The current mesh of the object
Reimplemented from Renderer.
Definition at line 55 of file OpenGL.cpp.
{
    shader.setMat4("model", newModel);
    // bind appropriate textures
    unsigned int diffuseNr = 1;
    unsigned int specularNr = 1;
    unsigned int normalNr = 1;
    unsigned int heightNr = 1;
    for (unsigned int i = 0; i < mesh.textures.size(); i++)
    {
        glActiveTexture(GL_TEXTURE0 + i); // active proper texture unit before binding
        // retrieve texture number (the N in diffuse_textureN)
        std::string number;
        std::string name = mesh.textures[i].type;
        if (name == "texture_diffuse")
            number = std::to_string(diffuseNr++);
        else if (name == "texture_specular")
            number = std::to_string(specularNr++); // transfer unsigned int to stream
        else if (name == "texture_normal")
            number = std::to_string(normalNr++); // transfer unsigned int to stream
        else if (name == "texture_height")
            number = std::to_string(heightNr++); // transfer unsigned int to stream
        // now set the sampler to the correct texture unit
        glUniform1i(glGetUniformLocation(shader.ID, (name + number).c_str()), i);
        // and finally bind the texture
        glBindTexture(GL_TEXTURE_2D, mesh.textures[i].id);
    }
    // draw mesh
    glBindVertexArray(mesh.VAO);
    glDrawElements(GL_TRIANGLES, mesh.indices.size(), GL_UNSIGNED_INT, 0);
    glBindVertexArray(0);
    // always good practice to set everything back to defaults once configured.
    glActiveTexture(GL_TEXTURE0);
}
RenderSkybox()
void OpenGL::RenderSkybox (unsigned int VAO, unsigned int texture) [virtual]
Renders the sky box.
Parameters
VAO - The vertex array object
texture - The texture number
Reimplemented from Renderer.
Definition at line 44 of file OpenGL.cpp.
{
    glDepthFunc(GL_LEQUAL);
    glBindVertexArray(VAO);
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_CUBE_MAP, texture);
    glDrawArrays(GL_TRIANGLES, 0, 36);
    glBindVertexArray(0);
    glDepthFunc(GL_LESS);
}
RenderTerrain()
void OpenGL::RenderTerrain (unsigned int VAO, int size) [virtual]
Renders the games terrain.
Parameters
VAO - The vertex array object
size - the size needed to render
Reimplemented from Renderer.
Definition at line 5 of file OpenGL.cpp.
{
    glPrimitiveRestartIndex(0xFFFFFFFFU);
    glEnable(GL_PRIMITIVE_RESTART);
    glBindVertexArray(VAO);
    glDrawElements(GL_TRIANGLES, size, GL_UNSIGNED_INT, 0);
    glBindVertexArray(0);
    glActiveTexture(GL_TEXTURE0);
}
SetShader()
void OpenGL::SetShader (Shader shader, View lens) [virtual]
Sets the shader and uses it.
Parameters
shader - The shader used
lens - The viewing information
Reimplemented from Renderer.
Definition at line 93 of file OpenGL.cpp.
{
    shader.use();
    shader.setMat4("projection", lens.GetProjection());
    shader.setMat4("view", lens.GetView());
    shader.setMat4("model", lens.GetModel());
}
References Shader::use().
SetShaderSkybox()
void OpenGL::SetShaderSkybox (Shader shader, View lens) [virtual]
Sets the shader and uses it for the skybox.
Parameters
shader - The shader used
lens - The viewing information
Reimplemented from Renderer.
Definition at line 114 of file OpenGL.cpp.
{
    glm::mat4 viewSky = glm::mat4(glm::mat3(lens.GetSkyview()));
    shader.use();
    shader.setMat4("view", viewSky);
    shader.setMat4("projection", lens.GetProjection());
}
References Shader::use().
SetShaderTerrain()
void OpenGL::SetShaderTerrain (Shader & shader, View lens) [virtual]
Sets up the shader for the terrain.
Parameters
shader - The shader used
lens - The viewing information
Reimplemented from Renderer.
Definition at line 101 of file OpenGL.cpp.
{
    shader.use();
    shader.setMat4("projection", lens.GetProjection());
    shader.setMat4("view", lens.GetView());
    glm::mat4 m = glm::mat4(1.0f);
    m = glm::scale(m, glm::vec3(0.2f));
    shader.setMat4("model", m);
    shader.setVec3("lightColor", 1.0f, 1.0f, 1.0f);
    shader.setVec3("lightPos", (256 * 12) / 2.0, 100.0f, (256 * 12) / 2.0);
    shader.setVec3("viewPos", lens.GetPosition());
}
References Shader::setVec3(), and Shader::use().
SetupMesh()
void OpenGL::SetupMesh (unsigned int & VAO, unsigned int & VBO, unsigned int & EBO, std::vector< Vertex > vertices, std::vector< unsigned int > indices) [virtual]
Sets an objects mesh.
Parameters
VAO - The vertex array object
VBO - The vertex buffer object
EBO - Another buffer
vertices - The vertex positions for the mesh
indices - The indice positons
Reimplemented from Renderer.
Definition at line 262 of file OpenGL.cpp.
{
    glGenVertexArrays(1, &VAO);
    glGenBuffers(1, &VBO);
    glGenBuffers(1, &EBO);
    glBindVertexArray(VAO);
    // load data into vertex buffers
    glBindBuffer(GL_ARRAY_BUFFER, VBO);
    // A great thing about structs is that their memory layout is sequential for all its items.
    // The effect is that we can simply pass a pointer to the struct and it translates perfectly to a glm::vec3/2 array which
    // again translates to 3/2 floats which translates to a byte array.
    glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(Vertex), &vertices[0], GL_STATIC_DRAW);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), &indices[0], GL_STATIC_DRAW);
    // set the vertex attribute pointers
    // vertex Positions
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)0);
    // vertex normals
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, Normal));
    // vertex texture coords
    glEnableVertexAttribArray(2);
    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, TexCoords));
    // vertex tangent
    glEnableVertexAttribArray(3);
    glVertexAttribPointer(3, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, Tangent));
    // vertex bitangent
    glEnableVertexAttribArray(4);
    glVertexAttribPointer(4, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, Bitangent));
    glBindVertexArray(0);
}
SkyboxSetup()
void OpenGL::SkyboxSetup (std::vector< float > skyVerts, std::vector< std::string > faces, unsigned int & VAO, unsigned int & VBO, unsigned int & texture, Shader & skyShader) [virtual]
Sets up the skybox.
Parameters
skyVerts - The vertice positions
faces - The texture file names
VAO - The vertex array object
VBO - The vertex buffer object
EBO - Another buffer
texture - The texture number
skyShader - The skybox shader
Reimplemented from Renderer.
Definition at line 176 of file OpenGL.cpp.
{
    if(Debugger::GetInstance()->debugToConsole) std::cout << "renderer size: " << skyVerts.size() << std::endl;
    glGenVertexArrays(1, &VAO);
    glGenBuffers(1, &VBO);
    glBindVertexArray(VAO);
    glBindBuffer(GL_ARRAY_BUFFER, VBO);
    glBufferData(GL_ARRAY_BUFFER, skyVerts.size() * sizeof(float), &skyVerts[0], GL_STATIC_DRAW);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)0);
    glGenTextures(1, &texture);
    glBindTexture(GL_TEXTURE_CUBE_MAP, texture);
    int width, height, nrChannels;
    for (unsigned int i = 0; i < faces.size(); i++) {
        unsigned char* data =
            stbi_load(faces[i].c_str(), &width, &height, &nrChannels, 0);
        if (data) {
            glTexImage2D(GL_TEXTURE_CUBE_MAP_POSITIVE_X + i, 0, GL_RGB, width,
                height, 0, GL_RGB, GL_UNSIGNED_BYTE, data);
            stbi_image_free(data);
        }
        else {
            std::cout << "Cubemap texture failed to load at path: " << faces[i]
                << std::endl;
            stbi_image_free(data);
        }
    }
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
    skyShader.use();
    skyShader.setInt("skybox", 0);
}
References Shader::setInt(), and Shader::use().
TerrainSetup()
void OpenGL::TerrainSetup (std::vector< glm::vec3 > totalData, std::vector< unsigned int > Indices, unsigned int & VAO, unsigned int & VBO, unsigned int & EBO) [virtual]
Sets up the terrain data.
Parameters
totalData - The vec3 data information
indices - The list of positions for the totalData
VAO - The vertex array object
VBO - The vertex buffer object
EBO - Another buffer
Reimplemented from Renderer.
Definition at line 145 of file OpenGL.cpp.
{
    glGenVertexArrays(1, &VAO);
    glGenBuffers(1, &VBO);
    glGenBuffers(1, &EBO);
    glBindVertexArray(VAO);
    glBindBuffer(GL_ARRAY_BUFFER, VBO);
    glBufferData(GL_ARRAY_BUFFER, totalData.size() * sizeof(glm::vec3), &totalData[0], GL_STATIC_DRAW);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, Indices.size() * sizeof(unsigned int), &Indices[0], GL_STATIC_DRAW);
    //postion attributes
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 12 * sizeof(float), (void*)0);
    glEnableVertexAttribArray(0);
    //color attributes
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 12 * sizeof(float), (void*)(3 * sizeof(float)));
    glEnableVertexAttribArray(1);
    //texture attributes
    glVertexAttribPointer(2, 3, GL_FLOAT, GL_FALSE, 12 * sizeof(float), (void*)(6 * sizeof(float)));
    glEnableVertexAttribArray(2);
    //normal attributes
    glVertexAttribPointer(3, 3, GL_FLOAT, GL_FALSE, 12 * sizeof(float), (void*)(9 * sizeof(float)));
    glEnableVertexAttribArray(3);
}
TextureFromFile()
unsigned int OpenGL::TextureFromFile (std::string path, const std::string & directory) [virtual]
grabs a texture from a specified file path
Parameters
path - the path to the texture
directory - the directory of the file
Returns
unsigned int
Reimplemented from Renderer.
Definition at line 216 of file OpenGL.cpp.
{
    std::string filename = path;
    if(Debugger::GetInstance()->debugToConsole) std::cout << "OpenGL.cpp::INFO::" << filename << std::endl; //debug
    filename = directory + '/' + filename;
    if(Debugger::GetInstance()->debugToConsole) std::cout << "OpenGL.cpp::INFO::" << filename << std::endl; //debug
    stbi_set_flip_vertically_on_load(false);
    unsigned int textureID;
    glGenTextures(1, &textureID);
    int width, height, nrComponents;
    unsigned char* data = stbi_load(filename.c_str(), &width, &height, &nrComponents, 0);
    if (data)
    {
        GLenum format;
        if (nrComponents == 1)
            format = GL_RED;
        else if (nrComponents == 3)
            format = GL_RGB;
        else if (nrComponents == 4)
            format = GL_RGBA;
        glBindTexture(GL_TEXTURE_2D, textureID);
        glTexImage2D(GL_TEXTURE_2D, 0, (int)format, width, height, 0, format, GL_UNSIGNED_BYTE, data);
        glGenerateMipmap(GL_TEXTURE_2D);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
        stbi_image_free(data);
    }
    else
    {
        std::cout << "OpenGL.cpp::ERROR::Texture failed to load at path: " << path << std::endl;
        stbi_image_free(data);
    }
    return textureID;
}
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/OpenGL.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/OpenGL.cpp