Enemy Class Reference
Abstract GameObject class for enemies.
#include <Enemy.h>
Public Member Functions
Enemy (glm::vec3 p, glm::vec3 rot, Renderer *gameRenderer, std::string script)
Enemy constructor that takes various parameters.
Enemy (glm::vec3 p, glm::vec3 rot, float s, Renderer *gameRenderer, std::string script, float h, float a, std::string state)
Enemy constructor that takes various parameters.
~Enemy ()
destructor that deallocates resource upon deletion of enemy object
stateMachine< Enemy > * getFSM () const
gets and returns the finite state machine of the enemy
void Update (float time)
Updates the game object with functionality.
int getHealth ()
gets and returns the health value of the enemy
void setHealth (int h)
sets the health value for the enemy
glm::vec3 GetPos () const
Gets the position of the game object.
void SetPos (glm::vec3 p)
Sets the position of the game object.
void decreaseHealth (int health)
decreases the value of health by the integer provided as a parameter
void Render (View lens, float time, Renderer *gameRenderer)
makes use of the view information and graphics renderer to render the enemy to the screen
void SetState (int num)
sets the animation state to the value provided as parameter, whether it be an integer or an enumerated type
void setAlive (bool a)
sets the boolean value of the alive variable
void SetKillFSM (bool k)
sets the boolean value of the killFSM variable
bool isAlive ()
gets and returns the alive boolean value
float GetDeltaTime () const
gets and returns the value of deletaTime
float Distance ()
gets and returns the distance between the enemy and the first person player camera
float DistanceBetween (glm::vec3 otherPos)
gets and returns the distance between a given position and an enemy position
glm::vec3 getCamPos ()
gets and returns the position of the first person player camera
bool handleMessage (const Telegram message)
allows the enemy to handle messages it receives from other entities
bool moveTo (glm::vec3 &curPos, const glm::vec3 &targetPos, glm::vec3 &curVelocity, float time, float offset, std::string type)
allows the enemy to move from its current position to a specified target position
void pursue (const glm::vec3 &evaderPos, glm::vec3 &pursuerPos, const glm::vec3 &evaderVelocity, glm::vec3 &pursuerVelocity, float time, float offset, std::string type)
allows the enemy to pursue an evading target
bool flee (glm::vec3 &curPos, const glm::vec3 &pursuerPos, glm::vec3 &curVelocity, float fleeSpeed, float time, std::string type)
allows the enemy to flee from a pursuing entity
bool evade (glm::vec3 &evaderPos, const glm::vec3 &pursuerPos, glm::vec3 &evaderVelocity, const glm::vec3 &pursuerVelocity, float time, std::string type)
allows the enemy to evade a pursuing entity. Serves as a flee that moves from the predicted future position of the pursuer
void setWander (double wanderRadius, double wanderDistance, double wanderJitter)
a function used to set the values that will be used in the wander movement function
bool wander (glm::vec3 &position, glm::vec3 &velocity, float time, std::string type)
a function used to set the values that will be used in the wander movement function
glm::vec3 getVelocity () const
gets and returns the velocity vector
void setVelocity (glm::vec3 v)
function that allows you to set the values of the velocity vector
glm::vec3 getEnemyVelocity () const
gets and returns the enemy velocity vector
void setEnemyVelocity (glm::vec3 v)
function that allows you to set the values of the enemyVelocity vector
float getDirection () const
gets and returns the direction in which the enemy is facing
void setDirection (float dir)
sets the direction in which the enemy is facing
bool getGlobalFlag () const
gets and returns the value of the globalFlag (globalFlag is used to ensure that globalState changes don't get stuck in a loop)
void setGlobalFlag (bool flag)
sets the value of the globalFlag
bool getToken () const
gets and returns the value of the token
void setToken (bool t)
sets the value of the token
bool getDeathAnim () const
gets and returns the value of the deathAnim flag
void setDeathAnim (bool d)
sets the value of the deathAnim boolean
int getTimer () const
gets and returns the value of the timer
void setTimer (int t)
sets the value of the timer
int incrementTimer ()
increments the timer value
int getCheck () const
gets and returns the value of the check
void setCheck (int c)
sets the value of the check
int incrementCheck ()
increments the check value
void ChangeState (std::string state)
a function that changes the enemy state to the state provided to the function provided as a parameter
bool CheckPrevState (std::string state)
a function that returns the previous state so long as the state parameter provided matches a valid state, otherwise it returns false
float LookDirection (std::string type)
a function that returns the looking direction of the enemy dependant on which string is provided
void SendMessage (int message, std::string type)
a function that will send a message from the enemy to a specified gameObject type
void SetMoving (bool m)
sets the value of the moving boolean value, which is set to true when the enemy is moving towards the enemy that has seen the player and called for their help
bool GetMoving ()
gets and returns the value of moving
glm::vec3 getNewPos ()
gets and returns the the newPos vector
void setNewPos (glm::vec3 p)
sets the value of the newPos vector
bool Kill ()
returns the killFSM bool value
virtual std::string StreamValues ()
Returns the streamed values for the game object.
std::string ReturnState ()
returns the string value of the state that the FSM is currently in
float GetAccuracy ()
Gets the accuracy factor of an enemy.
void SetAccuracy (float a)
Sets the accuracy factor of an enemy.
bool GetAliveStatus ()
Returns if the enemy is alive or not.
void SetAliveStatus (bool s)
Sets the alive value for the enemy.
int GetDamage ()
Gets Damage value for the enemy.
void SetDamage (int d)
sets Damage value for the enemy
void SetFireWeapon (bool f)
Sets if the weapon is firing or not.
bool GetFireWeapon ()
Gets if the weapon is firing.
void ResetEnemy (glm::vec3 spawn)
Resets the enemy object, mainly used for pooling so that we dont need to allocate memory for new enemies each time we spawn one, we just reset the one that died.
std::string getDifficulty ()
returns the current game difficulty as a string
Public Attributes
glm::vec3 enemyVelocity = { 6.0f, 0.0f, 0.0f }
enemyVelocity
glm::vec3 velocity = { 4.0f, 0.0f, 0.0f }
cam Velocity
glm::vec3 newPos
the position the enemy is heading too
LuaRef wanderLua = NULL
Wander lua reference.
LuaRef alert = NULL
alert lua reference
LuaRef chase = NULL
chase lua reference
LuaRef fleeLua = NULL
flee lua reference
LuaRef attack = NULL
attack lua reference
LuaRef die = NULL
die lua reference
LuaRef global = NULL
global lua reference
LuaRef init = NULL
initilise lua reference
bool startTimer
Time for when the enemy will despawn.
Detailed Description
Abstract GameObject class for enemies.
Author
Christopher Logan
Version
01
Date
25/03/2021
Todo
Todo Add enemy functionality
@bugs none to be seen
Author
Dylan Blereau
Version
02
Date
05/05/21
Added enemy FSM and messaging functionality
Definition at line 39 of file Enemy.h.
Constructor & Destructor Documentation
Enemy() [1/2]
Enemy::Enemy (glm::vec3 p, glm::vec3 rot, Renderer * gameRenderer, std::string script)
Enemy constructor that takes various parameters.
Parameters
p - reperesents the vector position
rot - represents the rotation vector
gameRenderer - a pointer to the game engine renderer
script - a string repesenting the path to the enemy lua script
Definition at line 3 of file Enemy.cpp.
                                                                             : GameObject(p, rot, 0, gameRenderer)
{
    lua_State* L = LuaManager::getInstance().getLuaState();
    SetScriptName(script);
    int h = 50;
    int a = 5;
    bool living = true, weap = false;
    LuaRef setup = NULL;
    if (!luaL_dofile(L, script.c_str()))
    {
        wanderLua = getGlobal(L, "wander");
        alert = getGlobal(L, "alert");
        chase = getGlobal(L, "chase");
        fleeLua = getGlobal(L, "flee");
        attack = getGlobal(L, "attack");
        die = getGlobal(L, "die");
        global = getGlobal(L, "global");
        setup = getGlobal(L, "setup");
        LuaRef type = getGlobal(L, "check");
        LuaRef rot = getGlobal(L, "rotate");
        LuaRef alv = getGlobal(L, "alive");
        LuaRef weapon = getGlobal(L, "weapon");
        LuaRef mod = getGlobal(L, "model");
        LuaRef tex = getGlobal(L, "texture");
        LuaRef vert = getGlobal(L, "vertShader");
        LuaRef frag = getGlobal(L, "fragShader");
        LuaRef hel = getGlobal(L, "health");
        LuaRef amm = getGlobal(L, "ammo");
        LuaRef acc = getGlobal(L, "accuracy");
        LuaRef dam = getGlobal(L, "damage");
        std::string file;
        std::string vertS;
        std::string fragS;
        std::string texture;
        bool check = false, rotate = false;
        if (type.isBool())
        {
            check = type.cast<bool>();
        }
        if (rot.isBool())
        {
            rotate = rot.cast<bool>();
        }
        if (alv.isBool())
        {
            living = alv.cast<bool>();
        }
        if (weapon.isBool())
        {
            weap = weapon.cast<bool>();
        }
        if (mod.isString())
        {
            file = mod.cast<std::string>();
        }
        if (vert.isString())
        {
            vertS = vert.cast<std::string>();
        }
        if (frag.isString())
        {
            fragS = frag.cast<std::string>();
        }
        if (tex.isString())
        {
            texture = tex.cast<std::string>();
        }
        if (hel.isNumber())
        {
            h = hel.cast<int>();
        }
        if (amm.isNumber())
        {
            a = amm.cast<int>();
        }
        if (acc.isNumber())
        {
            accuracyFactor = acc.cast<float>();
        }
        if (dam.isNumber())
        {
            damage = dam.cast<int>();
        }
        Model tempModel(file, gameRenderer, check, texture, true);
        SetModel(tempModel);
        Shader tempShader(vertS.c_str(), fragS.c_str());
        SetShader(tempShader);
        SetRotate(rotate);
        if (weap)
        {
            LuaRef WeapMod = getGlobal(L, "weaponModel");
            LuaRef weapTex = getGlobal(L, "weaponTexture");
            std::string weaponModel;
            std::string weaponTexture;
            if (WeapMod.isString())
            {
                weaponModel = WeapMod.cast<std::string>();
            }
            if (weapTex.isString())
            {
                weaponTexture = weapTex.cast<std::string>();
            }
            Model tempWeaponModel(weaponModel, gameRenderer, check, weaponTexture, true);
            wModel = tempWeaponModel;
        }
    }
    else if (!luaL_dofile(L, "./res/scripts/gameobjects/enemy_default.lua"))
    {
                wanderLua = getGlobal(L, "wander");
        alert = getGlobal(L, "alert");
        chase = getGlobal(L, "chase");
        fleeLua = getGlobal(L, "flee");
        attack = getGlobal(L, "attack");
        die = getGlobal(L, "die");
        global = getGlobal(L, "global");
        setup = getGlobal(L, "setup");
        LuaRef type = getGlobal(L, "check");
        LuaRef rot = getGlobal(L, "rotate");
        LuaRef alv = getGlobal(L, "alive");
        LuaRef weapon = getGlobal(L, "weapon");
        LuaRef mod = getGlobal(L, "model");
        LuaRef tex = getGlobal(L, "texture");
        LuaRef vert = getGlobal(L, "vertShader");
        LuaRef frag = getGlobal(L, "fragShader");
        LuaRef hel = getGlobal(L, "health");
        LuaRef amm = getGlobal(L, "ammo");
        LuaRef acc = getGlobal(L, "accuracy");
        LuaRef dam = getGlobal(L, "damage");
        std::string file;
        std::string vertS;
        std::string fragS;
        std::string texture;
        bool check = false, rotate = false;
        if (type.isBool())
        {
            check = type.cast<bool>();
        }
        if (rot.isBool())
        {
            rotate = rot.cast<bool>();
        }
        if (alv.isBool())
        {
            living = alv.cast<bool>();
        }
        if (weapon.isBool())
        {
            weap = weapon.cast<bool>();
        }
        if (mod.isString())
        {
            file = mod.cast<std::string>();
        }
        if (vert.isString())
        {
            vertS = vert.cast<std::string>();
        }
        if (frag.isString())
        {
            fragS = frag.cast<std::string>();
        }
        if (tex.isString())
        {
            texture = tex.cast<std::string>();
        }
        if (hel.isNumber())
        {
            h = hel.cast<int>();
        }
        if (amm.isNumber())
        {
            a = amm.cast<int>();
        }
        if (acc.isNumber())
        {
            accuracyFactor = acc.cast<float>();
        }
        if (dam.isNumber())
        {
            damage = dam.cast<int>();
        }
        Model tempModel(file, gameRenderer, check, texture, true);
        SetModel(tempModel);
        Shader tempShader(vertS.c_str(), fragS.c_str());
        SetShader(tempShader);
        SetRotate(rotate);
        if (weap)
        {
            LuaRef WeapMod = getGlobal(L, "weaponModel");
            LuaRef weapTex = getGlobal(L, "weaponTexture");
            std::string weaponModel;
            std::string weaponTexture;
            if (WeapMod.isString())
            {
                weaponModel = WeapMod.cast<std::string>();
            }
            if (weapTex.isString())
            {
                weaponTexture = weapTex.cast<std::string>();
            }
            Model tempWeaponModel(weaponModel, gameRenderer, check, weaponTexture, true);
            wModel = tempWeaponModel;
        }
    }
    else
    {
        std::cout << "ERROR::NO_ENEMY_SCRIPTS_FOUND" << std::endl;
    }
    enemyFSM = new stateMachine<Enemy>(this);
    enemyFSM->setCurrentState(&wander_state::getInstance());
    enemyFSM->setGlobalState(&global_state::getInstance());
    health = h;
    healthHold = h;
    ammo = a;
    alive = living;
    hasWeapon = weap;
    startTimer = false;
    deathtimer = 2;
    weaponTimer = 0.5f;
    accuracyFactor = 0.35f;
    damage = 10;
    if (setup.isFunction())
    {
        setup(this);
    }
}
References Model::Model(), Shader::Shader(), and startTimer.
Enemy() [2/2]
Enemy::Enemy (glm::vec3 p, glm::vec3 rot, float s, Renderer * gameRenderer, std::string script, float h, float a, std::string state)
Enemy constructor that takes various parameters.
Parameters
p - reperesents the vector position
rot - represents the rotation vector
s - represents the enemy scale
gameRenderer - a pointer to the game engine renderer
script - a string repesenting the path to the enemy lua script
h - represents the enemy health
a - represents the enemy ammo
state - reperesents the enemy state
Definition at line 281 of file Enemy.cpp.
                                                                                                                         : GameObject(p, rot, s, gameRenderer)
{
    lua_State* L = LuaManager::getInstance().getLuaState();
    SetScriptName(script);
    bool living = true, weap = false;
    LuaRef setup = NULL;
    if (!luaL_dofile(L, script.c_str()))
    {
        wanderLua = getGlobal(L, "wander");
        alert = getGlobal(L, "alert");
        chase = getGlobal(L, "chase");
        fleeLua = getGlobal(L, "flee");
        attack = getGlobal(L, "attack");
        die = getGlobal(L, "die");
        global = getGlobal(L, "global");
        setup = getGlobal(L, "setup");
        LuaRef type = getGlobal(L, "check");
        LuaRef rot = getGlobal(L, "rotate");
        LuaRef alv = getGlobal(L, "alive");
        LuaRef weapon = getGlobal(L, "weapon");
        LuaRef mod = getGlobal(L, "model");
        LuaRef tex = getGlobal(L, "texture");
        LuaRef vert = getGlobal(L, "vertShader");
        LuaRef frag = getGlobal(L, "fragShader");
        LuaRef hel = getGlobal(L, "health");
        LuaRef amm = getGlobal(L, "ammo");
        LuaRef acc = getGlobal(L, "accuracy");
        LuaRef dam = getGlobal(L, "damage");
        std::string file;
        std::string vertS;
        std::string fragS;
        std::string texture;
        bool check = false, rotate = false;
        if (type.isBool())
        {
            check = type.cast<bool>();
        }
        if (rot.isBool())
        {
            rotate = rot.cast<bool>();
        }
        if (alv.isBool())
        {
            living = alv.cast<bool>();
        }
        if (weapon.isBool())
        {
            weap = weapon.cast<bool>();
        }
        if (mod.isString())
        {
            file = mod.cast<std::string>();
        }
        if (vert.isString())
        {
            vertS = vert.cast<std::string>();
        }
        if (frag.isString())
        {
            fragS = frag.cast<std::string>();
        }
        if (tex.isString())
        {
            texture = tex.cast<std::string>();
        }
        if (hel.isNumber())
        {
            h = hel.cast<int>();
        }
        if (amm.isNumber())
        {
            a = amm.cast<int>();
        }
        if (acc.isNumber())
        {
            accuracyFactor = acc.cast<float>();
        }
        if (dam.isNumber())
        {
            damage = dam.cast<int>();
        }
        Model tempModel(file, gameRenderer, check, texture, true);
        SetModel(tempModel);
        Shader tempShader(vertS.c_str(), fragS.c_str());
        SetShader(tempShader);
        SetRotate(rotate);
        if (weap)
        {
            LuaRef WeapMod = getGlobal(L, "weaponModel");
            LuaRef weapTex = getGlobal(L, "weaponTexture");
            std::string weaponModel;
            std::string weaponTexture;
            if (WeapMod.isString())
            {
                weaponModel = WeapMod.cast<std::string>();
            }
            if (weapTex.isString())
            {
                weaponTexture = weapTex.cast<std::string>();
            }
            Model tempWeaponModel(weaponModel, gameRenderer, check, weaponTexture, true);
            wModel = tempWeaponModel;
        }
    }
    else if (!luaL_dofile(L, "./res/scripts/gameobjects/enemy_default.lua"))
    {
        wanderLua = getGlobal(L, "wander");
        alert = getGlobal(L, "alert");
        chase = getGlobal(L, "chase");
        fleeLua = getGlobal(L, "flee");
        attack = getGlobal(L, "attack");
        die = getGlobal(L, "die");
        global = getGlobal(L, "global");
        setup = getGlobal(L, "setup");
        LuaRef type = getGlobal(L, "check");
        LuaRef rot = getGlobal(L, "rotate");
        LuaRef alv = getGlobal(L, "alive");
        LuaRef weapon = getGlobal(L, "weapon");
        LuaRef mod = getGlobal(L, "model");
        LuaRef tex = getGlobal(L, "texture");
        LuaRef vert = getGlobal(L, "vertShader");
        LuaRef frag = getGlobal(L, "fragShader");
        LuaRef hel = getGlobal(L, "health");
        LuaRef amm = getGlobal(L, "ammo");
        LuaRef acc = getGlobal(L, "accuracy");
        LuaRef dam = getGlobal(L, "damage");
        std::string file;
        std::string vertS;
        std::string fragS;
        std::string texture;
        bool check = false, rotate = false;
        if (type.isBool())
        {
            check = type.cast<bool>();
        }
        if (rot.isBool())
        {
            rotate = rot.cast<bool>();
        }
        if (alv.isBool())
        {
            living = alv.cast<bool>();
        }
        if (weapon.isBool())
        {
            weap = weapon.cast<bool>();
        }
        if (mod.isString())
        {
            file = mod.cast<std::string>();
        }
        if (vert.isString())
        {
            vertS = vert.cast<std::string>();
        }
        if (frag.isString())
        {
            fragS = frag.cast<std::string>();
        }
        if (tex.isString())
        {
            texture = tex.cast<std::string>();
        }
        if (hel.isNumber())
        {
            h = hel.cast<int>();
        }
        if (amm.isNumber())
        {
            a = amm.cast<int>();
        }
        if (acc.isNumber())
        {
            accuracyFactor = acc.cast<float>();
        }
        if (dam.isNumber())
        {
            damage = dam.cast<int>();
        }
        Model tempModel(file, gameRenderer, check, texture, true);
        SetModel(tempModel);
        Shader tempShader(vertS.c_str(), fragS.c_str());
        SetShader(tempShader);
        SetRotate(rotate);
        if (weap)
        {
            LuaRef WeapMod = getGlobal(L, "weaponModel");
            LuaRef weapTex = getGlobal(L, "weaponTexture");
            std::string weaponModel;
            std::string weaponTexture;
            if (WeapMod.isString())
            {
                weaponModel = WeapMod.cast<std::string>();
            }
            if (weapTex.isString())
            {
                weaponTexture = weapTex.cast<std::string>();
            }
            Model tempWeaponModel(weaponModel, gameRenderer, check, weaponTexture, true);
            wModel = tempWeaponModel;
        }
    }
    else
    {
        std::cout << "ERROR::NO_ENEMY_SCRIPTS_FOUND" << std::endl;
    }
    enemyFSM = new stateMachine<Enemy>(this);
    enemyFSM->setCurrentState(&wander_state::getInstance());
    ChangeState(state);
    enemyFSM->setGlobalState(&global_state::getInstance());
    health = h;
    healthHold = health;
    ammo = a;
    alive = living;
    hasWeapon = weap;
    startTimer = false;
    deathtimer = 2;
    weaponTimer = 0.5f;
    accuracyFactor = 0.35f;
    damage = 10;
    if (setup.isFunction())
    {
        setup(this);
    }
    //Set state
}
References ChangeState(), Model::Model(), Shader::Shader(), and startTimer.
Member Function Documentation
ChangeState()
void Enemy::ChangeState (std::string state)
a function that changes the enemy state to the state provided to the function provided as a parameter
Parameters
state - represents the state that the fsm will change to
Returns
bool
Definition at line 940 of file Enemy.cpp.
{
    if (state == "wander")
    {
        getFSM()->changeState(&wander_state::getInstance());
    }
    else if (state == "alert")
    {
        getFSM()->changeState(&alert_state::getInstance());
    }
    else if (state == "chase")
    {
        getFSM()->changeState(&chase_state::getInstance());
    }
    else if (state == "flee")
    {
        getFSM()->changeState(&flee_state::getInstance());
    }
    else if (state == "attack")
    {
        getFSM()->changeState(&attack_state::getInstance());
    }
    else if (state == "die")
    {
        getFSM()->changeState(&die_state::getInstance());
    }
    else if (state == "global")
    {
        getFSM()->changeState(&global_state::getInstance());
    }
}
Referenced by Enemy().
CheckPrevState()
bool Enemy::CheckPrevState (std::string state)
a function that returns the previous state so long as the state parameter provided matches a valid state, otherwise it returns false
Parameters
state - represents the state that the fsm will check to see if its the previous state
Returns
bool
Definition at line 972 of file Enemy.cpp.
{
    if (state == "wander")
    {
        return getFSM()->getPreviousState() == &wander_state::getInstance();
    }
    else if (state == "alert")
    {
        return getFSM()->getPreviousState() == &alert_state::getInstance();
    }
    else if (state == "chase")
    {
        return getFSM()->getPreviousState() == &chase_state::getInstance();
    }
    else if (state == "flee")
    {
        return getFSM()->getPreviousState() == &flee_state::getInstance();
    }
    else if (state == "attack")
    {
        return getFSM()->getPreviousState() == &attack_state::getInstance();
    }
    else if (state == "die")
    {
        return getFSM()->getPreviousState() == &die_state::getInstance();
    }
    else if (state == "global")
    {
        return getFSM()->getPreviousState() == &global_state::getInstance();
    }
    else
    {
        return false;
    }
}
decreaseHealth()
void Enemy::decreaseHealth (int health)
decreases the value of health by the integer provided as a parameter
Parameters
health - represents the value that health will be decreased by
Definition at line 650 of file Enemy.cpp.
{
    this->health -= health;
    if (this->health < 0)
    {
        this->health = 0;
    }
}
Distance()
float Enemy::Distance ()
gets and returns the distance between the enemy and the first person player camera
Returns
float
Definition at line 758 of file Enemy.cpp.
{
    glm::vec3 camPos(pPos.x, pPos.y, pPos.z);
    glm::vec3 modelPos(GetPos().x, GetPos().y, GetPos().z);
    glm::vec3 norm = glm::normalize(camPos - modelPos);
    velocity = (norm * 3.0f);
    
    float distance = glm::distance(camPos, modelPos);
    return distance;
}
DistanceBetween()
float Enemy::DistanceBetween (glm::vec3 otherPos)
gets and returns the distance between a given position and an enemy position
Returns
float
Definition at line 773 of file Enemy.cpp.
{
    glm::vec3 oPos = otherPos;
    glm::vec3 modelPos(GetPos().x, GetPos().y, GetPos().z);
    float distance = glm::distance(oPos, modelPos);
    if(Debugger::GetInstance()->debugFSMToConsole)
    {
        std::cout << "Distance: " << distance << " Positions other: " << " " << otherPos.x << " " << otherPos.y << " "
                  << otherPos.z << ", Position enemy: " << modelPos.x << " " << modelPos.y << " " << modelPos.z << " "
                  << std::endl;
    }
    else if(Debugger::GetInstance()->debugInfoToLogFile)
    {
        Debugger::GetInstance()->AppendLogger("Enemy.cpp", "Distance: " + std::to_string(distance) + " Positions other: " + Debugger::GetInstance()->DebugVec3(otherPos) + ", Position enemy: " + Debugger::GetInstance()->DebugVec3(modelPos));
    }
    return distance;
}
References Debugger::debugFSMToConsole, and Debugger::debugInfoToLogFile.
evade()
bool Enemy::evade (glm::vec3 & evaderPos, const glm::vec3 & pursuerPos, glm::vec3 & evaderVelocity, const glm::vec3 & pursuerVelocity, float time, std::string type)
allows the enemy to evade a pursuing entity. Serves as a flee that moves from the predicted future position of the pursuer
Parameters
evaderPos - the vector representing the current position of the enemy
pursuerPos - the vector representing the position of the pursuer
evaderVelocity - represents the velocity of the evader
pursuerVelocity - represents the velocity of the pursuer
time - represents the time
Returns
bool
Definition at line 903 of file Enemy.cpp.
{
    //distance between pursuer and evader
    glm::vec3 toPursuer = pursuerPos - evaderPos;
    float lookAheadTime = toPursuer.length() / (evaderVelocity.length() + pursuerVelocity.length());
    return(flee(evaderPos, pursuerPos + pursuerVelocity * lookAheadTime, evaderVelocity, evaderVelocity.length(), time, type));
}
flee()
bool Enemy::flee (glm::vec3 & curPos, const glm::vec3 & pursuerPos, glm::vec3 & curVelocity, float fleeSpeed, float time, std::string type)
allows the enemy to flee from a pursuing entity
Parameters
curPos - the vector representing the current position of the enemy
pursuerPos - the vector representing the position of the pursuer
curVelocity - represent the velocity of the pursuer
fleeSpeed - represents the fleeSpeed that is used to set the velocity
time - represents the time that is multiplied by velocity to update the current position
Returns
bool
Definition at line 888 of file Enemy.cpp.
{
    glm::vec3 fromPursuer = curPos - pursuerPos;
    float panic = 100.0f * 100.0f;
    if (fromPursuer.length() > panic)
        return false;
    fromPursuer = glm::normalize(fromPursuer);
    curVelocity = fromPursuer * fleeSpeed;
    SetPos(curPos + curVelocity * time);
    return true;
}
GetAccuracy()
float Enemy::GetAccuracy () [inline]
Gets the accuracy factor of an enemy.
Returns
accuracy factor
Definition at line 428 of file Enemy.h.
{return accuracyFactor;}
Referenced by Scene::EnemyFireWeapon().
GetAliveStatus()
bool Enemy::GetAliveStatus () [inline]
Returns if the enemy is alive or not.
Returns
bool alive
Definition at line 440 of file Enemy.h.
{ return alive; }
getCamPos()
glm::vec3 Enemy::getCamPos () [inline]
gets and returns the position of the first person player camera
Returns
glm::vec3
Definition at line 173 of file Enemy.h.
{ return pPos; }
getCheck()
int Enemy::getCheck () const [inline]
gets and returns the value of the check
Returns
int
Definition at line 343 of file Enemy.h.
{ return check; }
GetDamage()
int Enemy::GetDamage () [inline]
Gets Damage value for the enemy.
Returns
int damage
Definition at line 452 of file Enemy.h.
{ return damage; }
getDeathAnim()
bool Enemy::getDeathAnim () const [inline]
gets and returns the value of the deathAnim flag
Returns
bool
Definition at line 313 of file Enemy.h.
{ return deathAnim; }
GetDeltaTime()
float Enemy::GetDeltaTime () const [inline]
gets and returns the value of deletaTime
Returns
float
Definition at line 153 of file Enemy.h.
{ return deltaTime; }
getDifficulty()
std::string Enemy::getDifficulty ()
returns the current game difficulty as a string
Returns
string difficulty
Definition at line 1117 of file Enemy.cpp.
{
    switch (singleton<Manager>::getInstance().difficulty)
    {
    case Manager::Difficulty::hard:
        return "Hard";
    case Manager::Difficulty::normal:
        return "Normal";
    case Manager::Difficulty::easy:
        return "Easy";
    default:
        break;
    }
}
getDirection()
float Enemy::getDirection () const [inline]
gets and returns the direction in which the enemy is facing
Returns
float
Definition at line 277 of file Enemy.h.
{ return direction; }
getEnemyVelocity()
glm::vec3 Enemy::getEnemyVelocity () const [inline]
gets and returns the enemy velocity vector
Returns
glm::vec3
Definition at line 265 of file Enemy.h.
{ return enemyVelocity; }
GetFireWeapon()
bool Enemy::GetFireWeapon () [inline]
Gets if the weapon is firing.
Returns
bool fireweapon
Definition at line 470 of file Enemy.h.
{ return fireWeapon; }
getFSM()
stateMachine<Enemy>* Enemy::getFSM () const [inline]
gets and returns the finite state machine of the enemy
Returns
stateMachine<Enemy>*
Definition at line 74 of file Enemy.h.
{ return enemyFSM; }
getGlobalFlag()
bool Enemy::getGlobalFlag () const [inline]
gets and returns the value of the globalFlag (globalFlag is used to ensure that globalState changes don't get stuck in a loop)
Returns
bool
Definition at line 289 of file Enemy.h.
{ return globalFlag; }
getHealth()
int Enemy::getHealth () [inline]
gets and returns the health value of the enemy
Returns
int health
Definition at line 87 of file Enemy.h.
{ return health;}
GetMoving()
bool Enemy::GetMoving () [inline]
gets and returns the value of moving
Returns
bool
Definition at line 395 of file Enemy.h.
{ return moving; }
getNewPos()
glm::vec3 Enemy::getNewPos () [inline]
gets and returns the the newPos vector
Returns
glm::vec3
Definition at line 401 of file Enemy.h.
{ return newPos; }
GetPos()
glm::vec3 Enemy::GetPos () const [inline]
Gets the position of the game object.
Returns
pPos - position of the game object
Definition at line 101 of file Enemy.h.
{ return GameObject::GetPos(); }
getTimer()
int Enemy::getTimer () const [inline]
gets and returns the value of the timer
Returns
int
Definition at line 325 of file Enemy.h.
{ return timer; }
Referenced by Update().
getToken()
bool Enemy::getToken () const [inline]
gets and returns the value of the token
Returns
bool
Definition at line 301 of file Enemy.h.
{ return token; }
getVelocity()
glm::vec3 Enemy::getVelocity () const [inline]
gets and returns the velocity vector
Returns
glm::vec3
Definition at line 253 of file Enemy.h.
{ return velocity; }
handleMessage()
bool Enemy::handleMessage (const Telegram message) [virtual]
allows the enemy to handle messages it receives from other entities
Parameters
message - represents the message sent to the enemy
Returns
bool
Reimplemented from GameObject.
Definition at line 1034 of file Enemy.cpp.
{
    if (Debugger::GetInstance()->debugToConsole)
    {
        std::cout << message.sender << " has sent a message to " << GetId() << " " << message.msg << ", distance: " << DistanceBetween(message.pos) << std::endl;
    }
    else if(Debugger::GetInstance()->debugInfoToLogFile)
    {
        std::string s;
        s += std::to_string(message.sender) + " has sent a message to " + std::to_string(GetId()) + " " + std::to_string(message.msg) + ", distance: " + std::to_string(DistanceBetween(message.pos));
        Debugger::GetInstance()->AppendLogger("Enemy.cpp", s);
    }
    if (enemyFSM->handleMessage(message))
    {
        if (DistanceBetween(message.pos) <= 1000.0f)
        {
            newPos = message.pos;
            moving = true;
        }
        return true;
    }
    else
        return false;
}
References Debugger::AppendLogger(), Debugger::debugInfoToLogFile, and Debugger::debugToConsole.
incrementCheck()
int Enemy::incrementCheck () [inline]
increments the check value
Returns
int
Definition at line 355 of file Enemy.h.
{ return check++; }
incrementTimer()
int Enemy::incrementTimer () [inline]
increments the timer value
Returns
int
Definition at line 337 of file Enemy.h.
{ return timer++; }
Referenced by Update().
isAlive()
bool Enemy::isAlive () [inline]
gets and returns the alive boolean value
Returns
bool
Definition at line 147 of file Enemy.h.
{ return alive; };
Kill()
bool Enemy::Kill () [virtual]
returns the killFSM bool value
Returns
bool
Reimplemented from GameObject.
Definition at line 1029 of file Enemy.cpp.
{
    return alive;
}
LookDirection()
float Enemy::LookDirection (std::string type)
a function that returns the looking direction of the enemy dependant on which string is provided
Parameters
type - represents the type of thing that should be looked at (which in this case in the enemy looking at the player)
Returns
float
Definition at line 1008 of file Enemy.cpp.
{
    if (type == "player")
    {
        return atan2(getVelocity().z, getVelocity().x);
    }
    else if (type == "playerOpp")
    {
        return atan2(-getVelocity().z, -getVelocity().x);
    }
    else
    {
        return atan2(enemyVelocity.z, enemyVelocity.x);
    }
}
moveTo()
bool Enemy::moveTo (glm::vec3 & curPos, const glm::vec3 & targetPos, glm::vec3 & curVelocity, float time, float offset, std::string type)
allows the enemy to move from its current position to a specified target position
Parameters
curPos - the vector representing the current position of the enemy
targetPos - the vector representing the target position to move to
curVelocity - represents the enemy's current velocity
time - represents the time used to calculate the displacement
offset - the distance that the character should maintain between itself and its target
Returns
bool
Definition at line 793 of file Enemy.cpp.
{
    //calc heading from character position to target
    glm::vec3 target = targetPos - curPos;
    target = glm::normalize(target);
    if (target.x == 0 && target.y == 0 && target.z == 0)
        return true;
    //calc new velocity and new character position
    curVelocity = target * glm::length(curVelocity);
    glm::vec3 displacement = curVelocity * time;
    glm::vec3 vec = curPos + displacement;
    if (type == "Player")
        setVelocity(curVelocity);
    else
        setEnemyVelocity(curVelocity);
    // calculate real target position
    glm::vec3 realTargetPos = targetPos - target * offset;
    // calculate the direction from vec to realTargetPos
    glm::vec3 toRealTarget = realTargetPos - vec;
    toRealTarget = glm::normalize(toRealTarget);
    if (toRealTarget.x == 0 && toRealTarget.y == 0 && toRealTarget.z == 0)
    {
        if(realTargetPos.y < 25.0f)
        {
            curPos = realTargetPos;
        }
        curPos = realTargetPos;
        SetPos(curPos);
        return true;
    }
    //check to see whether vec has gone pass the realTargetPos
    float dp = glm::dot(toRealTarget, target);
    if (dp < 0.0)
    {
        if(realTargetPos.y < 25.0f)
        {
            curPos = realTargetPos;
        }
        SetPos(curPos);
        return true;
    }
    //std::cout << curPos.x << " " << curPos.y << " " << curPos.z << " | " << vec.x << " " << vec.y << " " << vec.z << std::endl;
    // vec has not yet passed realTargetPos
    if(vec.y < 25.0f)
    {
        curPos = vec;
    }
    SetPos(curPos);
    return false;
}
pursue()
void Enemy::pursue (const glm::vec3 & evaderPos, glm::vec3 & pursuerPos, const glm::vec3 & evaderVelocity, glm::vec3 & pursuerVelocity, float time, float offset, std::string type)
allows the enemy to pursue an evading target
Parameters
evaderPos - the vector representing the position of the evader (the first-person camera)
pursuerPos - the vector representing the position of the pursuer (the enemy)
evaderVelocity - represents the velocity of the evader
pursuerVelocity - represent the velocity of the pursuer
time - represents the time used to calculate the displacement
offset - the distance that the enemy should maintain between itself and its target
Definition at line 853 of file Enemy.cpp.
{
    double lookAheadTime;
    //distance between evader and pursuer
    glm::vec3 toEvader = evaderPos - pursuerPos;
    //compute two agents headings
    glm::vec3 pursuerHeading = pursuerVelocity;
    pursuerHeading = glm::normalize(pursuerHeading);
    glm::vec3 evaderHeading = evaderVelocity;
    evaderHeading = glm::normalize(evaderHeading);
    //compute angle between two agents
    double relativeHeading = glm::dot(pursuerHeading, evaderHeading);
    //std::cout << "relativeHeading = " << relativeHeading << std::endl;
    //std::cout << "Evader Velocity Length: " << glm::length(evaderVelocity) << std::endl;
    //determine if evader is facing pursuer
    if ((relativeHeading < -0.95) || glm::length(evaderVelocity) == 1)
    {
        moveTo(pursuerPos, evaderPos, pursuerVelocity, time, offset, type);
        //std::cout << "In eyesight" << std::endl;
    }
    else
    {
        lookAheadTime = (glm::length(toEvader)) / (glm::length(evaderVelocity) + glm::length(pursuerVelocity));
        moveTo(pursuerPos, evaderPos + evaderVelocity * (float)lookAheadTime, pursuerVelocity, time, offset, type);
        //std::cout << "outta eyesight" << std::endl;
    }
}
Render()
void Enemy::Render (View lens, float time, Renderer * gameRenderer) [virtual]
makes use of the view information and graphics renderer to render the enemy to the screen
Parameters
lens - holds the information that allows you to project and view the model
time - represents deltatime, which is the difference between the previous frame and the current frame
gameRenderer - a pointer to the renderer which is used to render the enemy model
Reimplemented from GameObject.
Definition at line 661 of file Enemy.cpp.
{
    pPos = lens.GetPosition();
    deltaTime = time;
    //if(Debugger::GetInstance()->debugFSMToConsole) std::cout << Distance() << std::endl;
    if (alive)
    {
        Model temp = GetModel();
        Shader s = GetShader();
        temp.Render(lens, s, GetPos(), GetRotation(), GetScale(), GetRotate(), time, direction, gameRenderer, false);
        if (hasWeapon)
        {
            wModel.Render(lens, s, GetPos(), GetRotation(), GetScale(), GetRotate(), time, direction, gameRenderer, false);
        }
        SetShader(s);
        SetModel(temp);
    }
}
ResetEnemy()
void Enemy::ResetEnemy (glm::vec3 spawn)
Resets the enemy object, mainly used for pooling so that we dont need to allocate memory for new enemies each time we spawn one, we just reset the one that died.
Parameters
vec3 spawn which is used to set the new reset positions of the enemy
Definition at line 1061 of file Enemy.cpp.
{
    SetPos(spawn);
    health = healthHold;
    std::cout << healthHold << std::endl;
    enemyFSM = new stateMachine<Enemy>(this);
    enemyFSM->setCurrentState(&wander_state::getInstance());
    enemyFSM->setGlobalState(&global_state::getInstance());
    SetState(2);
    alive = true;
    startTimer = false;
    deathtimer = 2;
}
References SetState(), and startTimer.
ReturnState()
std::string Enemy::ReturnState ()
returns the string value of the state that the FSM is currently in
Returns
std::string
Definition at line 1075 of file Enemy.cpp.
{
    if (getFSM()->getCurrentState() == &global_state::getInstance())
    {
        return "global";
    }
    else if (getFSM()->getCurrentState() == &wander_state::getInstance())
    {
        return "wander";
    }
    else if (getFSM()->getCurrentState() == &chase_state::getInstance())
    {
        return "chase";
    }
    else if (getFSM()->getCurrentState() == &flee_state::getInstance())
    {
        return "flee";
    }
    else if (getFSM()->getCurrentState() == &alert_state::getInstance())
    {
        return "alert";
    }
    else if (getFSM()->getCurrentState() == &die_state::getInstance())
    {
        return "die";
    }
    else if (getFSM()->getCurrentState() == &attack_state::getInstance())
    {
        return "attack";
    }
    else
    {
        return "";
    }
}
SendMessage()
void Enemy::SendMessage (int message, std::string type)
a function that will send a message from the enemy to a specified gameObject type
Parameters
message - refers to the message being sent
type - refers to the type of gameobject the message is being sent to
Definition at line 1024 of file Enemy.cpp.
{
    singleton<MessageDispatcher>::getInstance().DisbatchMsgAllOfType(GetId(), message, type);
}
SetAccuracy()
void Enemy::SetAccuracy (float a) [inline]
Sets the accuracy factor of an enemy.
Parameters
a for the accuracy value
Definition at line 434 of file Enemy.h.
{ accuracyFactor = a; }
setAlive()
void Enemy::setAlive (bool a) [inline]
sets the boolean value of the alive variable
Parameters
a - represents the value that will be assigned to the alive boolean variable
Definition at line 132 of file Enemy.h.
{ alive = a; }
SetAliveStatus()
void Enemy::SetAliveStatus (bool s) [inline]
Sets the alive value for the enemy.
Parameters
bool s which is then set to alive
Definition at line 446 of file Enemy.h.
{ alive = s; }
setCheck()
void Enemy::setCheck (int c) [inline]
sets the value of the check
Parameters
c - represents the value you want to assign the check
Definition at line 349 of file Enemy.h.
{ check = c; }
SetDamage()
void Enemy::SetDamage (int d) [inline]
sets Damage value for the enemy
Parameters
int damage
Definition at line 458 of file Enemy.h.
{ damage = d; }
setDeathAnim()
void Enemy::setDeathAnim (bool d) [inline]
sets the value of the deathAnim boolean
Parameters
d - represents the value you want to set deathAnim
Definition at line 319 of file Enemy.h.
{ deathAnim = d; }
setDirection()
void Enemy::setDirection (float dir) [inline]
sets the direction in which the enemy is facing
Parameters
dir - reprsents the direction value you want to set
Definition at line 283 of file Enemy.h.
{ direction = dir;}
setEnemyVelocity()
void Enemy::setEnemyVelocity (glm::vec3 v) [inline]
function that allows you to set the values of the enemyVelocity vector
Parameters
v - represents the vector value you want to assign to enemyVelocity
Definition at line 271 of file Enemy.h.
{ enemyVelocity = v; }
SetFireWeapon()
void Enemy::SetFireWeapon (bool f) [inline]
Sets if the weapon is firing or not.
Parameters
bool f which is set to fireweapon
Definition at line 464 of file Enemy.h.
{ fireWeapon = f; }
Referenced by Scene::EnemyFireWeapon().
setGlobalFlag()
void Enemy::setGlobalFlag (bool flag) [inline]
sets the value of the globalFlag
Parameters
flag - represents the value you want to set globalFlag
Definition at line 295 of file Enemy.h.
{ globalFlag = flag; }
setHealth()
void Enemy::setHealth (int h) [inline]
sets the health value for the enemy
Parameters
int h
Definition at line 94 of file Enemy.h.
{ health = h; healthHold = health; }
SetKillFSM()
void Enemy::SetKillFSM (bool k) [inline]
sets the boolean value of the killFSM variable
Parameters
k - represents the value that will be assigned to the killFSM boolean variable
Definition at line 138 of file Enemy.h.
    {
        killFSM = k;
    };
SetMoving()
void Enemy::SetMoving (bool m) [inline]
sets the value of the moving boolean value, which is set to true when the enemy is moving towards the enemy that has seen the player and called for their help
Parameters
m - represents the value you want to assign the moving boolean
Definition at line 389 of file Enemy.h.
{ moving = m; }
setNewPos()
void Enemy::setNewPos (glm::vec3 p) [inline]
sets the value of the newPos vector
Parameters
p - represents the value you want to assign the newPos vector
Definition at line 407 of file Enemy.h.
{ newPos = p; }
SetPos()
void Enemy::SetPos (glm::vec3 p) [inline]
Sets the position of the game object.
Parameters
p - the glm::vec3 position to be set
Definition at line 106 of file Enemy.h.
{ GameObject::SetPos(p); }
SetState()
void Enemy::SetState (int num)
sets the animation state to the value provided as parameter, whether it be an integer or an enumerated type
Parameters
num - represents the num or enum that belongs to an animation state
Definition at line 680 of file Enemy.cpp.
{
    Model temp = GetModel();
    Md2Commands state;
    switch (num)
    {
    case 0:
        state = STAND;
        break;
    case 1:
        state = RUN;
        break;
    case 2:
        state = WALK;
        break;
    case 3:
        state = ATTACK;
        break;
    case 4:
        state = PAIN_A;
        break;
    case 5:
        state = PAIN_B;
        break;
    case 6:
        state = PAIN_C;
        break;
    case 7:
        state = JUMP;
        break;
    case 8:
        state = FLIP;
        break;
    case 9:
        state = SALUTE;
        break;
    case 10:
        state = FALLBACK;
        break;
    case 11:
        state = WAVE;
        break;
    case 12:
        state = POINTING;
        break;
    case 13:
        state = CROUCH_STAND;
        break;
    case 14:
        state = CROUCH_WALK;
        break;
    case 15:
        state = CROUCH_ATTACK;
        break;
    case 16:
        state = CROUCH_PAIN;
        break;
    case 17:
        state = CROUCH_DEATH;
        break;
    case 18:
        state = DEATH_FALLBACK;
        break;
    case 19:
        state = DEATH;
        break;
    case 20:
        state = DEATH_FALLBACKSLOW;
        break;
    default:
        state = WALK;
        break;
    }
    temp.SetState(state);
    SetModel(temp);
    wModel.SetState(state);
}
References Model::SetState().
Referenced by ResetEnemy().
setTimer()
void Enemy::setTimer (int t) [inline]
sets the value of the timer
Parameters
t - represents the value you want to assign the timer
Definition at line 331 of file Enemy.h.
{ timer = t; }
setToken()
void Enemy::setToken (bool t) [inline]
sets the value of the token
Parameters
t - represents the value you want to set token
Definition at line 307 of file Enemy.h.
{ token = t; }
Referenced by Update().
setVelocity()
void Enemy::setVelocity (glm::vec3 v) [inline]
function that allows you to set the values of the velocity vector
Parameters
v - represents the vector value you want to assign to velocity
Definition at line 259 of file Enemy.h.
{ velocity = v;}
setWander()
void Enemy::setWander (double wanderRadius, double wanderDistance, double wanderJitter)
a function used to set the values that will be used in the wander movement function
Parameters
wanderRadius - the radius of the wander circle
wanderDistance - the distance the wander circle is projected in front of the agent
wanderJitter - represents the max amount of the displacement
Definition at line 913 of file Enemy.cpp.
{
    this->wanderRadius = wanderRadius;
    this->wanderDistance = wanderDistance;
    this->wanderJitter = wanderJitter;
    double theta = ((rand()) / (RAND_MAX + 1.0)) * (2 * PI);
    wanderTarget = { cos(theta), 0, sin(theta) };
}
StreamValues()
std::string Enemy::StreamValues () [virtual]
Returns the streamed values for the game object.
Returns
streamed Values of the game object
Reimplemented from GameObject.
Definition at line 1111 of file Enemy.cpp.
{
    return GetType() + " " + GetScriptName() + " " + std::to_string(GetScale()) + " " + std::to_string(GetPos().x) + " " + std::to_string(GetPos().y) + " " + std::to_string(GetPos().z) + " " + std::to_string(health) + " " + std::to_string(ammo) + " " + ReturnState() + "\n";
}
Update()
void Enemy::Update (float time) [virtual]
Updates the game object with functionality.
Parameters
time - the time since the last frame (deltatime)
Reimplemented from GameObject.
Definition at line 572 of file Enemy.cpp.
{
    if(Debugger::GetInstance()->debugFSMToConsole)
    {
        std::cout << GetId() << " player has token = " << token << std::endl;
    }
    else if(Debugger::GetInstance()->debugInfoToLogFile)
    {
        Debugger::GetInstance()->AppendLogger("Enemy.cpp", std::to_string(GetId()) +" player has token = " + std::to_string(token));
    }
    //if (function.isTable())
    //{
    // function[1](this);
    //}
    if (alive)
    {
        if (!startTimer)
        {
            if (singleton<Manager>::getInstance().prevToken == "DoubleDamage" && singleton<Manager>::getInstance().timer >= 0)
            {
                setToken(true);
            }
            else
                setToken(false);
            if (killFSM == false)
                enemyFSM->update();
            else
            {
                if (Debugger::GetInstance()->debugFSMToConsole)
                {
                    std::cout << "Should be destroyed" << std::endl;
                }
                else if(Debugger::GetInstance()->debugInfoToLogFile)
                {
                    Debugger::GetInstance()->AppendLogger("Enemy.cpp", "Enemy FSM Should be destroyed");
                }
                std::cout << "hi2.1" << std::endl;
                if (getTimer() != 400)
                {
                    incrementTimer();
                    if (Debugger::GetInstance()->debugToConsole)
                    {
                        std::cout << "TIMER: " << getTimer() << std::endl;
                    }
                    else if(Debugger::GetInstance()->debugInfoToLogFile)
                    {
                        Debugger::GetInstance()->AppendLogger("Enemy.cpp", "Timer: " + std::to_string(getTimer()));
                    }
                }
                else if (getTimer() == 400)
                {
                    alive = false;
                }
            }
            if(GetModel().GetState().type == 3)
            {
                //If were attacking
                weaponTimer -= time;
                if(weaponTimer <= 0)
                {
                    weaponTimer = 0.5f;
                    fireWeapon = true;
                }
            }
        }
        else
        {
            deathtimer -= time;
            if (deathtimer <= 0)
                alive = false;
        }
    }
}
References Debugger::AppendLogger(), Debugger::debugFSMToConsole, Debugger::debugInfoToLogFile, Debugger::debugToConsole, getTimer(), incrementTimer(), setToken(), and startTimer.
wander()
bool Enemy::wander (glm::vec3 & position, glm::vec3 & velocity, float time, std::string type)
a function used to set the values that will be used in the wander movement function
Parameters
position - the position of the enemy
velocity - the velocity of the enemy
time - represents the time
Returns
bool
Definition at line 922 of file Enemy.cpp.
{
    float jitter = wanderJitter * time;
    wanderTarget += glm::vec3(randomClamped() * jitter, 0.0, randomClamped() * jitter);
    //reproject the new vector back on to a unit circle
    wanderTarget = glm::normalize(wanderTarget);
    glm::vec3 heading(velocity);
    heading = glm::normalize(heading);
    glm::vec3 wanderCircleWorldCentre = position + (heading * (float)wanderDistance);
    //project the wanderTarget to the enlarged wander circle in the world
    glm::vec3 targetWorld = wanderCircleWorldCentre + (wanderTarget * (float)wanderRadius);
    //move to the new target position
    moveTo(position, targetWorld, velocity, deltaTime, 0, type);
    return true;
}
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Enemy.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Enemy.cpp