Player Class Reference
Abstract GameObject class for the player.
#include <Player.h>
Public Member Functions
Player (glm::vec3 p, glm::vec3 rot, float s, Renderer *gameRenderer, std::string script)
Player constructor that takes various parameters.
Player (glm::vec3 p, glm::vec3 rot, float s, Renderer *gameRenderer, std::string script, float h, std::string state, int savedPoints, int savedTokens, int savedKills)
Player constructor that takes various parameters.
stateMachine< Player > * getFSM () const
gets and returns the finite state machine of the player
int getHealth ()
void setHealth (int h)
int getPoints ()
void increasePoints (int p)
int getMultiplier ()
void setMultiplier (int m)
int getDamage ()
void setDamage (int d)
int getKills ()
void incrementKillCount ()
int getTokensCollected ()
void incrementTokensCollected ()
void Update (float time)
Updates the classes functionality.
virtual void Render (View lens, float time, Renderer *gameRenderer)
makes use of the view information and graphics renderer to render the player to the screen
void SetState (Md2Commands state)
sets the animation state to the value provided as a parameter
void FireWeapon ()
sets the shooting animation when the weapon is fired
void BackToIdle ()
sets the idle animation when the weapon is not being fired
virtual std::string StreamValues ()
returns a string of data that is required for saving
void Reset ()
Resets the player game object.
void SetToken (bool tok)
Sets the token.
bool GetToken ()
Gets the if the player has the token.
void SetInstanceToken (std::string str)
Sets the instance token for the manager.
std::string GetInstanceToken ()
Returns the instance token.
std::string GetPrevInstanceToken ()
Gets the previous instance token.
void SetPrevInstanceToken (std::string str)
Sets the previous instance token.
float GetInstanceTimer ()
Gets the instance timer.
void SetInstanceSpeed (float speed)
Gets the instance speed.
void ChangeState (std::string state)
Changes the state of the ai.
Public Attributes
bool hasToken = true
check if player has token or not
LuaRef dd = NULL
LuaRef refill = NULL
LuaRef speedBoost = NULL
LuaRef death = NULL
LuaRef dp = NULL
LuaRef global = NULL
LuaRef mainState = NULL
Detailed Description
Abstract GameObject class for the player.
Author
Christopher Logan
Version
01
Date
25/03/2021
@bugs none to be seen
Todo
Todo need to add player fsm and functionality
Added FSM and functionality
Author
Dylan Blereau
Version
02
Date
17/05/2021
Definition at line 27 of file Player.h.
Constructor & Destructor Documentation
Player() [1/2]
Player::Player (glm::vec3 p, glm::vec3 rot, float s, Renderer * gameRenderer, std::string script)
Player constructor that takes various parameters.
Parameters
p - reperesents the position vector
rot - represents the rotation vector
s - represents the player scale
gameRenderer - a pointer to the game engine renderer
script - a string repesenting the path to the enemy lua script
Definition at line 3 of file Player.cpp.
                                                                                        : GameObject(p, rot, s, gameRenderer)
{
    SetScriptName(script);
    lua_State* L = LuaManager::getInstance().getLuaState();
    bool bull = false;
    if(!luaL_dofile(L, script.c_str()))
    {
        dd = getGlobal(L, "doubleDamage");
        refill = getGlobal(L, "healthRefill");
        speedBoost = getGlobal(L, "speedBoost");
        death = getGlobal(L, "death");
        dp = getGlobal(L, "doublePoints");
        global = getGlobal(L, "global");
        mainState = getGlobal(L, "mainState");
        LuaRef type = getGlobal(L, "check");
        LuaRef rot = getGlobal(L, "rotate");
        LuaRef bullet = getGlobal(L, "bullet");
        LuaRef mod = getGlobal(L, "model");
        LuaRef tex = getGlobal(L, "texture");
        LuaRef vert = getGlobal(L, "vertShader");
        LuaRef frag = getGlobal(L, "fragShader");
        LuaRef xRot = getGlobal(L, "xRotOffset");
        LuaRef yRot = getGlobal(L, "yRotOffset");
        LuaRef zRot = getGlobal(L, "zRotOffset");
        LuaRef yPos = getGlobal(L, "yPosOffset");
        std::string file;
        std::string vertS;
        std::string fragS;
        std::string texture;
        float xr = 0, yr = 0, zr = 0, yp = 0;
        bool check = false, rotate = false;
        if (type.isBool())
        {
            check = type.cast<bool>();
        }
        if (rot.isBool())
        {
            rotate = rot.cast<bool>();
        }
        if (bullet.isBool())
        {
            bull = bullet.cast<bool>();
        }
        if (mod.isString())
        {
            file = mod.cast<std::string>();
        }
        if (tex.isString())
        {
            texture = tex.cast<std::string>();
        }
        if (vert.isString())
        {
            vertS = vert.cast<std::string>();
        }
        if (frag.isString())
        {
            fragS = frag.cast<std::string>();
        }
        if (xRot.isNumber())
        {
            xr = xRot.cast<float>();
        }
        if (yRot.isNumber())
        {
            yr = yRot.cast<float>();
        }
        if (zRot.isNumber())
        {
            zr = zRot.cast<float>();
        }
        if (yPos.isNumber())
        {
            yp = yPos.cast<float>();
        }
        Model tempModel(file, gameRenderer, check, texture, true);
        SetModel(tempModel);
        Shader tempShader(vertS.c_str(), fragS.c_str());
        SetShader(tempShader);
        xRotationOffset = xr;
        yRotationOffset = yr;
        zRotationOffset = zr;
        yPositionOffset = yp;
        SetRotate(rotate);
        if (bull)
        {
            LuaRef bulletMod = getGlobal(L, "bulletModel");
            LuaRef bulletTex = getGlobal(L, "bulletTexture");
            std::string bulletModel;
            std::string bulletTexture;
            if (bulletMod.isString())
            {
                bulletModel = bulletMod.cast<std::string>();
            }
            if (bulletTex.isString())
            {
                bulletTexture = bulletTex.cast<std::string>();
            }
            Model tempBulletModel(bulletModel, gameRenderer, check, bulletTexture, true);
            bModel = tempBulletModel;
        }
        health = 100;
    }
    else if (!luaL_dofile(L, "./res/scripts/gameobjects/player_default.lua"))
    {
        dd = getGlobal(L, "doubleDamage");
        refill = getGlobal(L, "healthRefill");
        speedBoost = getGlobal(L, "speedBoost");
        death = getGlobal(L, "death");
        dp = getGlobal(L, "doublePoints");
        global = getGlobal(L, "global");
        mainState = getGlobal(L, "mainState");
        LuaRef type = getGlobal(L, "check");
        LuaRef rot = getGlobal(L, "rotate");
        LuaRef bullet = getGlobal(L, "bullet");
        LuaRef mod = getGlobal(L, "model");
        LuaRef tex = getGlobal(L, "texture");
        LuaRef vert = getGlobal(L, "vertShader");
        LuaRef frag = getGlobal(L, "fragShader");
        LuaRef xRot = getGlobal(L, "xRotOffset");
        LuaRef yRot = getGlobal(L, "yRotOffset");
        LuaRef zRot = getGlobal(L, "zRotOffset");
        LuaRef yPos = getGlobal(L, "yPosOffset");
        std::string file;
        std::string vertS;
        std::string fragS;
        std::string texture;
        float xr = 0, yr = 0, zr = 0, yp = 0;
        bool check = false, rotate = false;
        if (type.isBool())
        {
            check = type.cast<bool>();
        }
        if (rot.isBool())
        {
            rotate = rot.cast<bool>();
        }
        if(bullet.isBool())
        {
            bull = bullet.cast<bool>();
        }
        if (mod.isString())
        {
            file = mod.cast<std::string>();
        }
        if(tex.isString())
        {
            texture = tex.cast<std::string>();
        }
        if (vert.isString())
        {
            vertS = vert.cast<std::string>();
        }
        if (frag.isString())
        {
            fragS = frag.cast<std::string>();
        }
        if (xRot.isNumber())
        {
            xr = xRot.cast<float>();
        }
        if (yRot.isNumber())
        {
            yr = yRot.cast<float>();
        }
        if (zRot.isNumber())
        {
            zr = zRot.cast<float>();
        }
        if (yPos.isNumber())
        {
            yp = yPos.cast<float>();
        }
        Model tempModel(file, gameRenderer, check, texture, true);
        SetModel(tempModel);
        Shader tempShader(vertS.c_str(), fragS.c_str());
        SetShader(tempShader);
        xRotationOffset = xr;
        yRotationOffset = yr;
        zRotationOffset = zr;
        yPositionOffset = yp;
        SetRotate(rotate);
        if(bull)
        {
            LuaRef bulletMod = getGlobal(L, "bulletModel");
            LuaRef bulletTex = getGlobal(L, "bulletTexture");
            std::string bulletModel;
            std::string bulletTexture;
            if(bulletMod.isString())
            {
                bulletModel = bulletMod.cast<std::string>();
            }
            if(bulletTex.isString())
            {
                bulletTexture = bulletTex.cast<std::string>();
            }
            Model tempBulletModel(bulletModel, gameRenderer, check, bulletTexture, true);
            bModel = tempBulletModel;
        }
        health = 100;
    }
    else
    {
        std::cout << "ERROR::NO_PLAYER_SCRIPTS_FOUND" << std::endl;
    }
    playerFSM = new stateMachine<Player>(this);
    playerFSM->setCurrentState(&singleton<main>::getInstance());
    playerFSM->setGlobalState(&glob_state::getInstance());
    SetType("player");
    Update(0.0f);
    SetState(SHOOT);
    if (Debugger::GetInstance()->debugToConsole) std::cout << xRotationOffset << " " << yRotationOffset << " " << zRotationOffset << " " << yPositionOffset << std::endl;
}
References Model::Model(), SetState(), Shader::Shader(), and Update().
Player() [2/2]
Player::Player (glm::vec3 p, glm::vec3 rot, float s, Renderer * gameRenderer, std::string script, float h, std::string state, int savedPoints, int savedTokens, int savedKills)
Player constructor that takes various parameters.
Parameters
p - reperesents the position vector
rot - represents the rotation vector
s - represents the player scale
gameRenderer - a pointer to the game engine renderer
script - a string repesenting the path to the enemy lua script
h - represents player health
state - represents the player state
savedPoints - refers to the value of saved points
saveTokens - refers to the value of saved tokens
savedKills - refers to the value of saved kills
Definition at line 272 of file Player.cpp.
                                                                                                                                                                    : GameObject(p, rot, s, gameRenderer)
{
    SetScriptName(script);
    lua_State* L = LuaManager::getInstance().getLuaState();
    bool bull = false;
    if (!luaL_dofile(L, script.c_str()))
    {
        dd = getGlobal(L, "doubleDamage");
        refill = getGlobal(L, "healthRefill");
        speedBoost = getGlobal(L, "speedBoost");
        death = getGlobal(L, "death");
        dp = getGlobal(L, "doublePoints");
        global = getGlobal(L, "global");
        mainState = getGlobal(L, "mainState");
        LuaRef type = getGlobal(L, "check");
        LuaRef rot = getGlobal(L, "rotate");
        LuaRef bullet = getGlobal(L, "bullet");
        LuaRef mod = getGlobal(L, "model");
        LuaRef tex = getGlobal(L, "texture");
        LuaRef vert = getGlobal(L, "vertShader");
        LuaRef frag = getGlobal(L, "fragShader");
        LuaRef xRot = getGlobal(L, "xRotOffset");
        LuaRef yRot = getGlobal(L, "yRotOffset");
        LuaRef zRot = getGlobal(L, "zRotOffset");
        LuaRef yPos = getGlobal(L, "yPosOffset");
        std::string file;
        std::string vertS;
        std::string fragS;
        std::string texture;
        float xr = 0, yr = 0, zr = 0, yp = 0;
        bool check = false, rotate = false;
        if (type.isBool())
        {
            check = type.cast<bool>();
        }
        if (rot.isBool())
        {
            rotate = rot.cast<bool>();
        }
        if (bullet.isBool())
        {
            bull = bullet.cast<bool>();
        }
        if (mod.isString())
        {
            file = mod.cast<std::string>();
        }
        if (tex.isString())
        {
            texture = tex.cast<std::string>();
        }
        if (vert.isString())
        {
            vertS = vert.cast<std::string>();
        }
        if (frag.isString())
        {
            fragS = frag.cast<std::string>();
        }
        if (xRot.isNumber())
        {
            xr = xRot.cast<float>();
        }
        if (yRot.isNumber())
        {
            yr = yRot.cast<float>();
        }
        if (zRot.isNumber())
        {
            zr = zRot.cast<float>();
        }
        if (yPos.isNumber())
        {
            yp = yPos.cast<float>();
        }
        Model tempModel(file, gameRenderer, check, texture, true);
        SetModel(tempModel);
        Shader tempShader(vertS.c_str(), fragS.c_str());
        SetShader(tempShader);
        xRotationOffset = xr;
        yRotationOffset = yr;
        zRotationOffset = zr;
        yPositionOffset = yp;
        SetRotate(rotate);
        if (bull)
        {
            LuaRef bulletMod = getGlobal(L, "bulletModel");
            LuaRef bulletTex = getGlobal(L, "bulletTexture");
            std::string bulletModel;
            std::string bulletTexture;
            if (bulletMod.isString())
            {
                bulletModel = bulletMod.cast<std::string>();
            }
            if (bulletTex.isString())
            {
                bulletTexture = bulletTex.cast<std::string>();
            }
            Model tempBulletModel(bulletModel, gameRenderer, check, bulletTexture, true);
            bModel = tempBulletModel;
        }
        health = 100;
    }
    else if (!luaL_dofile(L, "./res/scripts/gameobjects/player_default.lua"))
    {
        dd = getGlobal(L, "doubleDamage");
        refill = getGlobal(L, "healthRefill");
        speedBoost = getGlobal(L, "speedBoost");
        death = getGlobal(L, "death");
        dp = getGlobal(L, "doublePoints");
        global = getGlobal(L, "global");
        mainState = getGlobal(L, "mainState");
        LuaRef type = getGlobal(L, "check");
        LuaRef rot = getGlobal(L, "rotate");
        LuaRef bullet = getGlobal(L, "bullet");
        LuaRef mod = getGlobal(L, "model");
        LuaRef tex = getGlobal(L, "texture");
        LuaRef vert = getGlobal(L, "vertShader");
        LuaRef frag = getGlobal(L, "fragShader");
        LuaRef xRot = getGlobal(L, "xRotOffset");
        LuaRef yRot = getGlobal(L, "yRotOffset");
        LuaRef zRot = getGlobal(L, "zRotOffset");
        LuaRef yPos = getGlobal(L, "yPosOffset");
        std::string file;
        std::string vertS;
        std::string fragS;
        std::string texture;
        float xr = 0, yr = 0, zr = 0, yp = 0;
        bool check = false, rotate = false;
        if (type.isBool())
        {
            check = type.cast<bool>();
        }
        if (rot.isBool())
        {
            rotate = rot.cast<bool>();
        }
        if (bullet.isBool())
        {
            bull = bullet.cast<bool>();
        }
        if (mod.isString())
        {
            file = mod.cast<std::string>();
        }
        if (tex.isString())
        {
            texture = tex.cast<std::string>();
        }
        if (vert.isString())
        {
            vertS = vert.cast<std::string>();
        }
        if (frag.isString())
        {
            fragS = frag.cast<std::string>();
        }
        if (xRot.isNumber())
        {
            xr = xRot.cast<float>();
        }
        if (yRot.isNumber())
        {
            yr = yRot.cast<float>();
        }
        if (zRot.isNumber())
        {
            zr = zRot.cast<float>();
        }
        if (yPos.isNumber())
        {
            yp = yPos.cast<float>();
        }
        Model tempModel(file, gameRenderer, check, texture, true);
        SetModel(tempModel);
        Shader tempShader(vertS.c_str(), fragS.c_str());
        SetShader(tempShader);
        xRotationOffset = xr;
        yRotationOffset = yr;
        zRotationOffset = zr;
        yPositionOffset = yp;
        SetRotate(rotate);
        if (bull)
        {
            LuaRef bulletMod = getGlobal(L, "bulletModel");
            LuaRef bulletTex = getGlobal(L, "bulletTexture");
            std::string bulletModel;
            std::string bulletTexture;
            if (bulletMod.isString())
            {
                bulletModel = bulletMod.cast<std::string>();
            }
            if (bulletTex.isString())
            {
                bulletTexture = bulletTex.cast<std::string>();
            }
            Model tempBulletModel(bulletModel, gameRenderer, check, bulletTexture, true);
            bModel = tempBulletModel;
        }
        health = 100;
    }
    else
    {
        std::cout << "ERROR::NO_PLAYER_SCRIPTS_FOUND" << std::endl;
    }
    playerFSM = new stateMachine<Player>(this);
    playerFSM->setCurrentState(&singleton<main>::getInstance());
    playerFSM->setGlobalState(&glob_state::getInstance());
    health = h;
    SetType("player");
    Update(0.0f);
    SetState(IDLE);
    kills = savedKills;
    points = savedPoints;
    tokensCollected = savedTokens;
    if (Debugger::GetInstance()->debugToConsole) std::cout << xRotationOffset << " " << yRotationOffset << " " << zRotationOffset << " " << yPositionOffset << std::endl;
}
References Model::Model(), SetState(), Shader::Shader(), and Update().
Member Function Documentation
getFSM()
stateMachine<Player>* Player::getFSM () const [inline]
gets and returns the finite state machine of the player
Returns
stateMachine<Player>*
Definition at line 59 of file Player.h.
{ return playerFSM; }
Render()
void Player::Render (View lens, float time, Renderer * gameRenderer) [virtual]
makes use of the view information and graphics renderer to render the player to the screen
Parameters
lens - holds the information that allows you to project and view the model
time - represents deltatime, which is the difference between the previous frame and the current frame
gameRenderer - a pointer to the renderer which is used to render the enemy model
Reimplemented from GameObject.
Definition at line 558 of file Player.cpp.
{
    glm::vec3 pos = lens.GetPosition();
    pos.y -= 0.05;
    SetRotation(glm::vec3(lens.GetRotation().z , 180 + lens.GetRotation().x *-1, -1 * lens.GetRotation().y));
    Model temp = GetModel();
    Shader s = GetShader();
    bModel.Render(lens, s, pos, GetRotation(), GetScale(), GetRotate(), time, 0, gameRenderer, true);
    temp.Render(lens, s, pos, GetRotation(), GetScale(), GetRotate(), time, 0, gameRenderer, true);
    SetShader(s);
    SetModel(temp);
}
SetState()
void Player::SetState (Md2Commands state)
sets the animation state to the value provided as a parameter
Parameters
state - represents the animation state
Definition at line 571 of file Player.cpp.
{
    Model temp = GetModel();
    temp.SetState(state);
    SetModel(temp);
    bModel.SetState(state);
}
References Model::SetState().
Referenced by BackToIdle(), FireWeapon(), and Player().
StreamValues()
virtual std::string Player::StreamValues () [inline], [virtual]
returns a string of data that is required for saving
Returns
std::string
Reimplemented from GameObject.
Definition at line 173 of file Player.h.
    {
        return GetType() + " " + GetScriptName() + " " + std::to_string(GetScale()) + " " + std::to_string(GetPos().x) + " " + std::to_string(GetPos().y) + " " + std::to_string(GetPos().z) + " " + std::to_string(health) + " STATE" + " " + std::to_string(points) + " " + std::to_string(kills) + " " + std::to_string(tokensCollected) + "\n";
    }
Update()
void Player::Update (float time) [virtual]
Updates the classes functionality.
Parameters
time - The time between frames
Reimplemented from GameObject.
Definition at line 544 of file Player.cpp.
{
    playerFSM->update();
 }
Referenced by Player().
The documentation for this class was generated from the following files:
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Player.h
C:/Users/chris/Documents/UNI/ICT397-Project/ICT397-Project-Engine/Player.cpp