#pragma once

//To include in all applications that use the TNAH-Engine!
#include "TNAH/Core/Core.h"

// --- TNAH Engine Components --- //
#include "TNAH/Application.h"
#include "TNAH/Core/Log.h"
#include "TNAH/Layers/Layer.h"
#include "TNAH/Layers/ImGuiLayer.h"

/*
#include "TNAH/BoundingBox.h"
#include "TNAH/Buffer.h"
#include "TNAH/Callbacks.h"
#include "TNAH/camera.h"
#include "TNAH/Debugger.h"
#include "TNAH/DebugGUI.h"
#include "TNAH/DynamicEnum.h"
#include "TNAH/Enemy.h"
#include "TNAH/EndScreenGUI.h"
#include "TNAH/enemyStates.h"
#include "TNAH/Engine.h"
#include "TNAH/ExitScreen.h"
#include "TNAH/Fbx.h"
#include "TNAH/GameAssetFactory.h"
#include "TNAH/GameGUI.h"
#include "TNAH/GameObject.h"
#include "TNAH/GameObjects.h"
#include "TNAH/GlfwWindow.h"
#include "TNAH/GUI.h"
#include "TNAH/Input.h"
#include "TNAH/luaManager.h"
#include "TNAH/MainMenuGUI.h"
#include "TNAH/Manager.h"
#include "TNAH/Md2.h"
#include "TNAH/Md2State.h"
#include "TNAH/MenuGUI.h"
#include "TNAH/Mesh.h"
#include "TNAH/MessageDispatcher.h"
#include "TNAH/Model.h"
#include "TNAH/OpenGL.h"
#include "TNAH/PhysicsEvents.h"
#include "TNAH/PhysicsManager.h"
#include "TNAH/Player.h"
#include "TNAH/PlayerStates.h"
#include "TNAH/Renderer.h"
#include "TNAH/Scene.h"
#include "TNAH/SettingsManager.h"
#include "TNAH/Singleton.h"
#include "TNAH/SingletonHeaders.h"
#include "TNAH/Singletons.h"
#include "TNAH/Skybox.h"
#include "TNAH/state.h"
#include "TNAH/stateMachine.h"
#include "TNAH/Static.h"
#include "TNAH/stb_image.h"
#include "TNAH/Telegram.h"
#include "TNAH/Terrain.h"
#include "TNAH/TextureLoader.h"
#include "TNAH/Time.h"
#include "TNAH/Timer.h"
#include "TNAH/Token.h"
#include "TNAH/View.h"
#include "TNAH/Water.h"
#include "TNAH/Weapon.h"
#include "TNAH/Window.h"
#include "TNAH/Windows.h"
*/
// --- Entry Point --- //
#include "TNAH/EntryPoint.h"




