var hierarchy =
[
    [ "BoundingBox", "class_bounding_box.html", null ],
    [ "Buffer", "class_buffer.html", null ],
    [ "Camera", "class_camera.html", null ],
    [ "Debugger", "class_debugger.html", null ],
    [ "DynamicEnum", "class_dynamic_enum.html", null ],
    [ "Engine", "class_engine.html", null ],
    [ "EntityManager", "class_entity_manager.html", null ],
    [ "ExampleAppConsole", "struct_example_app_console.html", null ],
    [ "ExampleAppDocuments", "struct_example_app_documents.html", null ],
    [ "ExampleAppLog", "struct_example_app_log.html", null ],
    [ "ExitScreen", "class_exit_screen.html", null ],
    [ "Fbx", "class_fbx.html", null ],
    [ "GameAssetFactory", "class_game_asset_factory.html", null ],
    [ "GameObject", "class_game_object.html", [
      [ "Enemy", "class_enemy.html", null ],
      [ "Player", "class_player.html", null ],
      [ "Static", "class_static.html", null ],
      [ "Token", "class_token.html", null ],
      [ "Water", "class_water.html", null ]
    ] ],
    [ "GUI", "class_g_u_i.html", [
      [ "DebugGUI", "class_debug_g_u_i.html", null ],
      [ "EndScreenGUI", "class_end_screen_g_u_i.html", null ],
      [ "GameGUI", "class_game_g_u_i.html", null ],
      [ "MenuGUI", "class_menu_g_u_i.html", null ]
    ] ],
    [ "ImBitArray< BITCOUNT >", "struct_im_bit_array.html", null ],
    [ "ImBitVector", "struct_im_bit_vector.html", null ],
    [ "ImChunkStream< T >", "struct_im_chunk_stream.html", null ],
    [ "ImChunkStream< ImGuiTableSettings >", "struct_im_chunk_stream.html", null ],
    [ "ImChunkStream< ImGuiWindowSettings >", "struct_im_chunk_stream.html", null ],
    [ "ImColor", "struct_im_color.html", null ],
    [ "ImDrawChannel", "struct_im_draw_channel.html", null ],
    [ "ImDrawCmd", "struct_im_draw_cmd.html", null ],
    [ "ImDrawCmdHeader", "struct_im_draw_cmd_header.html", null ],
    [ "ImDrawData", "struct_im_draw_data.html", null ],
    [ "ImDrawDataBuilder", "struct_im_draw_data_builder.html", null ],
    [ "ImDrawList", "struct_im_draw_list.html", null ],
    [ "ImDrawListSharedData", "struct_im_draw_list_shared_data.html", null ],
    [ "ImDrawListSplitter", "struct_im_draw_list_splitter.html", null ],
    [ "ImDrawVert", "struct_im_draw_vert.html", null ],
    [ "ImFont", "struct_im_font.html", null ],
    [ "ImFontAtlas", "struct_im_font_atlas.html", null ],
    [ "ImFontAtlasCustomRect", "struct_im_font_atlas_custom_rect.html", null ],
    [ "ImFontBuildDstData", "struct_im_font_build_dst_data.html", null ],
    [ "ImFontBuilderIO", "struct_im_font_builder_i_o.html", null ],
    [ "ImFontBuildSrcData", "struct_im_font_build_src_data.html", null ],
    [ "ImFontConfig", "struct_im_font_config.html", null ],
    [ "ImFontGlyph", "struct_im_font_glyph.html", null ],
    [ "ImFontGlyphRangesBuilder", "struct_im_font_glyph_ranges_builder.html", null ],
    [ "ImGuiColorMod", "struct_im_gui_color_mod.html", null ],
    [ "ImGuiContext", "struct_im_gui_context.html", null ],
    [ "ImGuiContextHook", "struct_im_gui_context_hook.html", null ],
    [ "ImGuiDataTypeInfo", "struct_im_gui_data_type_info.html", null ],
    [ "ImGuiDataTypeTempStorage", "struct_im_gui_data_type_temp_storage.html", null ],
    [ "ImGuiGroupData", "struct_im_gui_group_data.html", null ],
    [ "ImGuiInputTextCallbackData", "struct_im_gui_input_text_callback_data.html", null ],
    [ "ImGuiInputTextState", "struct_im_gui_input_text_state.html", null ],
    [ "ImGuiIO", "struct_im_gui_i_o.html", null ],
    [ "ImGuiLastItemDataBackup", "struct_im_gui_last_item_data_backup.html", null ],
    [ "ImGuiListClipper", "struct_im_gui_list_clipper.html", null ],
    [ "ImGuiMenuColumns", "struct_im_gui_menu_columns.html", null ],
    [ "ImGuiMetricsConfig", "struct_im_gui_metrics_config.html", null ],
    [ "ImGuiNavMoveResult", "struct_im_gui_nav_move_result.html", null ],
    [ "ImGuiNextItemData", "struct_im_gui_next_item_data.html", null ],
    [ "ImGuiNextWindowData", "struct_im_gui_next_window_data.html", null ],
    [ "ImGuiOldColumnData", "struct_im_gui_old_column_data.html", null ],
    [ "ImGuiOldColumns", "struct_im_gui_old_columns.html", null ],
    [ "ImGuiOnceUponAFrame", "struct_im_gui_once_upon_a_frame.html", null ],
    [ "ImGuiPayload", "struct_im_gui_payload.html", null ],
    [ "ImGuiPlotArrayGetterData", "struct_im_gui_plot_array_getter_data.html", null ],
    [ "ImGuiPopupData", "struct_im_gui_popup_data.html", null ],
    [ "ImGuiPtrOrIndex", "struct_im_gui_ptr_or_index.html", null ],
    [ "ImGuiResizeBorderDef", "struct_im_gui_resize_border_def.html", null ],
    [ "ImGuiResizeGripDef", "struct_im_gui_resize_grip_def.html", null ],
    [ "ImGuiSettingsHandler", "struct_im_gui_settings_handler.html", null ],
    [ "ImGuiShrinkWidthItem", "struct_im_gui_shrink_width_item.html", null ],
    [ "ImGuiSizeCallbackData", "struct_im_gui_size_callback_data.html", null ],
    [ "ImGuiStackSizes", "struct_im_gui_stack_sizes.html", null ],
    [ "ImGuiStorage", "struct_im_gui_storage.html", null ],
    [ "ImGuiStorage::ImGuiStoragePair", "struct_im_gui_storage_1_1_im_gui_storage_pair.html", null ],
    [ "ImGuiStyle", "struct_im_gui_style.html", null ],
    [ "ImGuiStyleMod", "struct_im_gui_style_mod.html", null ],
    [ "ImGuiStyleVarInfo", "struct_im_gui_style_var_info.html", null ],
    [ "ImGuiTabBar", "struct_im_gui_tab_bar.html", null ],
    [ "ImGuiTabBarSection", "struct_im_gui_tab_bar_section.html", null ],
    [ "ImGuiTabItem", "struct_im_gui_tab_item.html", null ],
    [ "ImGuiTableColumnSortSpecs", "struct_im_gui_table_column_sort_specs.html", null ],
    [ "ImGuiTableSortSpecs", "struct_im_gui_table_sort_specs.html", null ],
    [ "ImGuiTextBuffer", "struct_im_gui_text_buffer.html", null ],
    [ "ImGuiTextFilter", "struct_im_gui_text_filter.html", null ],
    [ "ImGuiTextFilter::ImGuiTextRange", "struct_im_gui_text_filter_1_1_im_gui_text_range.html", null ],
    [ "ImGuiViewport", "struct_im_gui_viewport.html", [
      [ "ImGuiViewportP", "struct_im_gui_viewport_p.html", null ]
    ] ],
    [ "ImGuiWindow", "struct_im_gui_window.html", null ],
    [ "ImGuiWindowSettings", "struct_im_gui_window_settings.html", null ],
    [ "ImGuiWindowTempData", "struct_im_gui_window_temp_data.html", null ],
    [ "ImNewWrapper", "struct_im_new_wrapper.html", null ],
    [ "ImPool< T >", "struct_im_pool.html", null ],
    [ "ImPool< ImGuiTabBar >", "struct_im_pool.html", null ],
    [ "ImPool< ImGuiTable >", "struct_im_pool.html", null ],
    [ "ImRect", "struct_im_rect.html", null ],
    [ "ImSpan< T >", "struct_im_span.html", null ],
    [ "ImSpanAllocator< CHUNKS >", "struct_im_span_allocator.html", null ],
    [ "ImVec1", "struct_im_vec1.html", null ],
    [ "ImVec2", "struct_im_vec2.html", null ],
    [ "ImVec2ih", "struct_im_vec2ih.html", null ],
    [ "ImVec4", "struct_im_vec4.html", null ],
    [ "ImVector< T >", "struct_im_vector.html", null ],
    [ "ImVector< char * >", "struct_im_vector.html", null ],
    [ "ImVector< char >", "struct_im_vector.html", null ],
    [ "ImVector< const char * >", "struct_im_vector.html", null ],
    [ "ImVector< float >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawChannel >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawCmd >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawIdx >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawList * >", "struct_im_vector.html", null ],
    [ "ImVector< ImDrawVert >", "struct_im_vector.html", null ],
    [ "ImVector< ImFont * >", "struct_im_vector.html", null ],
    [ "ImVector< ImFontAtlasCustomRect >", "struct_im_vector.html", null ],
    [ "ImVector< ImFontConfig >", "struct_im_vector.html", null ],
    [ "ImVector< ImFontGlyph >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiColorMod >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiContextHook >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiGroupData >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiID >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiItemFlags >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiOldColumnData >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiOldColumns >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiPopupData >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiPtrOrIndex >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiSettingsHandler >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiShrinkWidthItem >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiStorage::ImGuiStoragePair >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiStyleMod >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiTabItem >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiTextFilter::ImGuiTextRange >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiViewportP * >", "struct_im_vector.html", null ],
    [ "ImVector< ImGuiWindow * >", "struct_im_vector.html", null ],
    [ "ImVector< ImTextureID >", "struct_im_vector.html", null ],
    [ "ImVector< ImU32 >", "struct_im_vector.html", null ],
    [ "ImVector< ImVec2 >", "struct_im_vector.html", null ],
    [ "ImVector< ImVec4 >", "struct_im_vector.html", null ],
    [ "ImVector< ImWchar >", "struct_im_vector.html", null ],
    [ "ImVector< int >", "struct_im_vector.html", null ],
    [ "ImVector< MyDocument >", "struct_im_vector.html", null ],
    [ "ImVector< unsigned char >", "struct_im_vector.html", null ],
    [ "Input", "class_input.html", null ],
    [ "luaManager", "classlua_manager.html", null ],
    [ "LuaManager", "class_lua_manager.html", null ],
    [ "MainMenuGUI", "class_main_menu_g_u_i.html", null ],
    [ "Manager", "class_manager.html", null ],
    [ "Md2", "class_md2.html", null ],
    [ "Md2Animation", "struct_md2_animation.html", null ],
    [ "Md2Frame", "struct_md2_frame.html", null ],
    [ "Md2State", "struct_md2_state.html", null ],
    [ "Md2Values", "struct_md2_values.html", null ],
    [ "Md2Vertex", "struct_md2_vertex.html", null ],
    [ "Mesh", "class_mesh.html", null ],
    [ "MessageDispatcher", "class_message_dispatcher.html", null ],
    [ "Model", "class_model.html", null ],
    [ "ModelInfo", "struct_model_info.html", null ],
    [ "MyDocument", "struct_my_document.html", null ],
    [ "Renderer", "class_renderer.html", [
      [ "OpenGL", "class_open_g_l.html", null ]
    ] ],
    [ "Scene", "class_scene.html", null ],
    [ "SettingsManager", "class_settings_manager.html", null ],
    [ "Shader", "class_shader.html", null ],
    [ "singleton< T >", "classsingleton.html", null ],
    [ "Skybox", "class_skybox.html", null ],
    [ "State< entity >", "class_state.html", null ],
    [ "state", "classstate.html", null ],
    [ "State< Enemy >", "class_state.html", [
      [ "alert", "classalert.html", null ],
      [ "attack", "classattack.html", null ],
      [ "chase", "classchase.html", null ],
      [ "die", "classdie.html", null ],
      [ "flee", "classflee.html", null ],
      [ "global", "classglobal.html", null ],
      [ "wander", "classwander.html", null ]
    ] ],
    [ "State< Player >", "class_state.html", [
      [ "SpeedUp", "class_speed_up.html", null ],
      [ "death", "classdeath.html", null ],
      [ "doubleDamage", "classdouble_damage.html", null ],
      [ "doublePoints", "classdouble_points.html", null ],
      [ "glob", "classglob.html", null ],
      [ "healthRefill", "classhealth_refill.html", null ],
      [ "main", "classmain.html", null ]
    ] ],
    [ "stateMachine< entity >", "classstate_machine.html", null ],
    [ "stateMachine< Enemy >", "classstate_machine.html", null ],
    [ "stateMachine< Player >", "classstate_machine.html", null ],
    [ "STB_TexteditState", "struct_s_t_b___textedit_state.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "stbrp_context", "structstbrp__context.html", null ],
    [ "stbrp_node", "structstbrp__node.html", null ],
    [ "stbrp_rect", "structstbrp__rect.html", null ],
    [ "StbTexteditRow", "struct_stb_textedit_row.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "StbUndoRecord", "struct_stb_undo_record.html", null ],
    [ "StbUndoState", "struct_stb_undo_state.html", null ],
    [ "Telegram", "struct_telegram.html", null ],
    [ "Terrain", "class_terrain.html", null ],
    [ "TextureLoader", "class_texture_loader.html", null ],
    [ "TextureMesh", "struct_texture_mesh.html", null ],
    [ "Time", "class_time.html", null ],
    [ "Timer", "class_timer.html", null ],
    [ "Vertex", "struct_vertex.html", null ],
    [ "View", "class_view.html", null ],
    [ "Weapon", "class_weapon.html", null ],
    [ "Window", "class_window.html", [
      [ "GlfwWindow", "class_glfw_window.html", null ]
    ] ]
];